### ISSUE TITLE
ConsolenSpam

### ISSUE THREAD

**Issue by Briareos82** [CodeCrafter47/BungeeTabListPlus#106]
[SCHWERWIEGEND] [BungeeTabListPlus] An error occurred while querying data from BungeePerms. Make sure you have configured BungeePerms to use it's uuidPlayerDB.
java.lang.NullPointerException
    at net.alpenblock.bungeeperms.User.buildSuffix(User.java:652)
    at net.alpenblock.bungeeperms.User.buildSuffix(User.java:595)
    at codecrafter47.bungeetablistplus.managers.PermissionManager.getSuffixFromBungeePerms(PermissionManager.java:340)
    at codecrafter47.bungeetablistplus.data.AbstractDataAccess.getRawValue(AbstractDataAccess.java:45)
    at codecrafter47.bungeetablistplus.managers.DataManager.updateData(DataManager.java:62)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
12:23:33 [SCHWERWIEGEND] [BungeeTabListPlus] An error occurred while querying data from BungeePerms. Make sure you

**Comment by CodeCrafter47** [comment]
This can be fixed by using the latest dev-build of BungeePerms.

**Comment by Briareos82** [comment]
Thx its work

**Comment by Briareos82** [comment]
one Problem more with BungeetablistPlus
permissionSource: BUKKIT
it show the most of my Rangs but wie use Permissionsex with SQL
when i use BUKKITPERMISSIONSEX it show only 5 Rangs

**Comment by CodeCrafter47** [comment]
As of version 2.5.0 of the plugin PermissionsEx support has been fixed. See [https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/PermissionsEx](https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/PermissionsEx) for more information.
