### ISSUE TITLE
Internal Error Stack Trace on version 253

### ISSUE THREAD

**Issue by ataranlen** [CodeCrafter47/BungeeTabListPlus#119]
Bungee #1176
BungeeTabListPlus: 253

```

15:25:30 [SEVERE] [BungeeTabListPlus] An internal error occurred! Please send the following StackTrace to the developer in order to help resolving the problem
java.lang.RuntimeException: Not in EventLoop
    at codecrafter47.bungeetablistplus.tablisthandler.logic.TabListLogic.failIfNotInEventLoop(TabListLogic.java:83)
    at codecrafter47.bungeetablistplus.tablisthandler.logic.TabListLogic.onPlayerListPacket(TabListLogic.java:111)
    at codecrafter47.bungeetablistplus.tablisthandler.logic.TabListHandler.onPlayerListPacket(TabListHandler.java:48)
    at codecrafter47.bungeetablistplus.tablisthandler.logic.RewriteLogic.onPlayerListPacket(RewriteLogic.java:92)
    at codecrafter47.bungeetablistplus.protocol.PacketListener.decode(PacketListener.java:58)
    at codecrafter47.bungeetablistplus.protocol.PacketListener.decode(PacketListener.java:35)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:883)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:389)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:305)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by CodeCrafter47** [comment]
Does this still happen in 2.5.4?

**Comment by ataranlen** [comment]
I don't believe I've seen it in the new version. If I do, I'll open a new ticket.
