### ISSUE TITLE
headerAnimationUpdateInterval is negative

### ISSUE THREAD

**Issue by mibby** [CodeCrafter47/BungeeTabListPlus#141]
Waterfall dev 59 (BungeeCord fork)

Not possible to disable the header and footer animation update interval? I just want to have static header/footer text. I set it to -1 assuming that would disable it.

```
11:11:24 [WARNING] [BungeeTabListPlus] Failed to load default.yml
Failed to validate config
 in 'reader', line 16, column 1:
    showTo: "all"
    ^
headerAnimationUpdateInterval is negative

    at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:223)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
    at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
    at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:441)
    at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig.read(YamlConfig.java:79)
    at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig.read(YamlConfig.java:75)
    at codecrafter47.bungeetablistplus.managers.TabListManager.loadTabLists(TabListManager.java:81)
    at codecrafter47.bungeetablistplus.BungeeTabListPlus.onEnable(BungeeTabListPlus.java:366)
    at codecrafter47.bungeetablistplus.BungeePlugin.onEnable(BungeePlugin.java:40)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:226)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:269)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.IllegalArgumentException: headerAnimationUpdateInterval is negative
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
    at codecrafter47.bungeetablistplus.config.Config.validate(Config.java:63)
    at codecrafter47.bungeetablistplus.config.FixedSizeConfig.validate(FixedSizeConfig.java:47)
    at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:221)
    ... 13 more
```

**Comment by CodeCrafter47** [comment]
Just set it to some high value.

**Comment by mibby** [comment]
But wouldn't it still be ticking?

**Comment by CodeCrafter47** [comment]
Yes, but if you set it for example to be updated every 60 seconds there won't be any noticeable performance impact, as the plugin will update it at least every 2 seconds to check for changed placeholders.

In a future update the plugin might ignore the headerAnimationUpdateInterval option if it detects that there is no animation, i.e. the header list contains only one element.

**Comment by CodeCrafter47** [comment]
> In a future update the plugin might ignore the headerAnimationUpdateInterval option if it detects that there is no animation, i.e. the header list contains only one element.

This is the case now (as of version 3.x.x). So I am closing this issue.
