### ISSUE TITLE
BungeeTabList spamming Bungee console with errors

### ISSUE THREAD

**Issue by Aoredon** [CodeCrafter47/BungeeTabListPlus#16]
[WARNING] [BungeeTabListPlus] §cAn internal error occurred! Please send the following StackTrace to the developer in order to help resolving the problem
java.lang.NullPointerException
	at net.alpenblock.bungeeperms.PermissionsManager.getUser(PermissionsManager.java:461)
	at codecrafter47.bungeetablistplus.managers.PermissionManager.getMainGroup(PermissionManager.java:49)
	at codecrafter47.bungeetablistplus.managers.PlayerManager.getPlayers(PlayerManager.java:79)
	at codecrafter47.bungeetablistplus.section.FillPlayersSection.getPlayers(FillPlayersSection.java:105)
	at codecrafter47.bungeetablistplus.section.FillPlayersSection.precalculate(FillPlayersSection.java:68)
	at codecrafter47.bungeetablistplus.config.TabListProvider.precalculateSections(TabListProvider.java:431)
	at codecrafter47.bungeetablistplus.config.TabListProvider.fillTabList(TabListProvider.java:75)
	at codecrafter47.bungeetablistplus.ResendThread.update(ResendThread.java:111)
	at codecrafter47.bungeetablistplus.ResendThread.run(ResendThread.java:66)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

I would attempt to fix this myself and make a pull request, but the null pointer exception could be created by a number of things and I don't have a good environment to test it in.

**Comment by CodeCrafter47** [comment]
Which version of BungeePerms?

**Comment by Aoredon** [comment]
The latest version which is BungeePerms 2.5.0, I think.

**Comment by CodeCrafter47** [comment]
Do you still have this issue? I think it happens because BungeePerms is configured to use uuids but uuidplayerdb has been set to none.
