### ISSUE TITLE
Java heap space - out of memory?

### ISSUE THREAD

**Issue by DanielAlves123** [CodeCrafter47/BungeeTabListPlus#190]
Hi, I think BTLP collects massive amount of data. 
`io.netty.handler.codec.DecoderException: java.lang.OutOfMemoryError: Java heap space
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space`

**Comment by CodeCrafter47** [comment]
Please provide a heap dump.

**Comment by DanielAlves123** [comment]
What?

**Comment by CodeCrafter47** [comment]
To analyze an out of memory error I need a heap dump. You can configure the jvm to create one when the out of memory error occurs.

But to be honest, I don't think there's an issue in BungeeTabListPlus.

**Comment by DanielAlves123** [comment]
It's the only thing that I changed, I added 4 tablist to the server. How to do this heap dump?

**Comment by DanielAlves123** [comment]
I created it: http://i.imgur.com/6nBRYXj.png. Also I use this starting line: `java -Xmx2G -server -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+AggressiveOpts -jar BungeeCord.jar`

**Comment by CodeCrafter47** [comment]
That's not a heap dump, that's an image. You might find this link helpful: [https://stackoverflow.com/questions/10944082/can-sun-jdk-generate-core-heap-dump-files-when-jvm-crashes](https://stackoverflow.com/questions/10944082/can-sun-jdk-generate-core-heap-dump-files-when-jvm-crashes). In your case the heap dump will be a file with ~2Gb, but you can compress it using zip.

**Comment by DanielAlves123** [comment]
I will send you this on SpigotMC, when this error occurs again.
