### ISSUE TITLE
Bug plugin

### ISSUE THREAD

**Issue by thebastien007** [CodeCrafter47/BungeeTabListPlus#217]
My error in consol:
```
19:08:35 [INFOS] Loaded plugin cmd_list version git:cmd_list:1.11-SNAPSHOT:5bc189f:1232 by SpigotMC
19:08:35 [AVERTISSEMENT] Error enabling plugin BungeeTabListPlus_BukkitBridge
java.lang.ClassNotFoundException: Do not install BungeeTabListPlus_BukkitBridge.jar on BungeeCord.
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:304)
at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:264)
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
19:08:35 [INFOS] Loaded plugin cmd_send version git:cmd_send:1.11-SNAPSHOT:5bc189f:1232 by SpigotMC
19:08:36 [AVERTISSEMENT] Forced host server null is not defined
```
Please, can you corrected that as soon as possible...
Thank's !

**Comment by CodeCrafter47** [comment]
Do not install BungeeTabListPlus_BukkitBridge.jar on BungeeCord.

**Comment by CodeCrafter47** [comment]
Installation instructions can be found at https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Installation
