### ISSUE TITLE
Get this issue when Installing bungeeperms

### ISSUE THREAD

**Issue by Luukth** [CodeCrafter47/BungeeTabListPlus#22]
20:27:19 [WARNING] [BungeeTabListPlus] An internal error occurred! Please send the following StackTrace to the developer in order to help resolving the problem
java.lang.ClassCastException: net.alpenblock.bungeeperms.platform.bungee.BungeePlugin cannot be cast to net.alpenblock.bungeeperms.BungeePerms
    at codecrafter47.bungeetablistplus.managers.PermissionManager.getMainGroup(PermissionManager.java:45)
    at codecrafter47.bungeetablistplus.config.TabListConfig.appliesTo(TabListConfig.java:237)
    at codecrafter47.bungeetablistplus.config.TabListProvider.appliesTo(TabListProvider.java:493)
    at codecrafter47.bungeetablistplus.managers.TabListManager.getTabListForPlayer(TabListManager.java:92)
    at codecrafter47.bungeetablistplus.ResendThread.update(ResendThread.java:102)
    at codecrafter47.bungeetablistplus.ResendThread.run(ResendThread.java:66)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

**Comment by CodeCrafter47** [comment]
This has already been fixed: efa1fd31c90fd7c79bd28e6dced001b75acdd766
