### ISSUE TITLE
BungeeTablistplus issued console error

### ISSUE THREAD

**Issue by Arobcher** [CodeCrafter47/BungeeTabListPlus#23]
[WARNING] [BungeeTabListPlus] &cAn internal error occurred! Please send t
he following StackTrace to the developer in order to help resolving the problem
java.lang.NoClassDefFoundError: net/alpenblock/bungeeperms/BungeePerms
    at codecrafter47.bungeetablistplus.managers.PermissionManager.getMainGroup(P
ermissionManager.java:45)
    at codecrafter47.bungeetablistplus.managers.PlayerManager.getPlayers(PlayerM
anager.java:79)
    at codecrafter47.bungeetablistplus.section.FillPlayersSection.getPlayers(Fil
lPlayersSection.java:105)
    at codecrafter47.bungeetablistplus.section.FillPlayersSection.precalculate(F
illPlayersSection.java:68)
    at codecrafter47.bungeetablistplus.config.TabListProvider.precalculateSectio
ns(TabListProvider.java:431)
    at codecrafter47.bungeetablistplus.config.TabListProvider.fillTabList(TabLis
tProvider.java:75)
    at codecrafter47.bungeetablistplus.ResendThread.update(ResendThread.java:111
)
    at codecrafter47.bungeetablistplus.ResendThread.run(ResendThread.java:66)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

 [WARNING] [BungeeTabListPlus] &cAn internal error occurred! Please send t
he following StackTrace to the developer in order to help resolving the problem
java.lang.NoClassDefFoundError: net/alpenblock/bungeeperms/BungeePerms
    at codecrafter47.bungeetablistplus.managers.PermissionManager.getMainGroup(P
ermissionManager.java:45)
    at codecrafter47.bungeetablistplus.variables.GroupVariable.getReplacement(Gr
oupVariable.java:35)
    at codecrafter47.bungeetablistplus.managers.VariablesManager.replacePlayerVa
riables(VariablesManager.java:165)
    at codecrafter47.bungeetablistplus.tablisthandler.TabList18v3.sendTablist(Ta
bList18v3.java:108)
    at codecrafter47.bungeetablistplus.ResendThread.update(ResendThread.java:113
)
    at codecrafter47.bungeetablistplus.ResendThread.run(ResendThread.java:66)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
@CodeCrafter47 Is there a solution?

**Comment by CodeCrafter47** [comment]
This has already been fixed: efa1fd31c90fd7c79bd28e6dced001b75acdd766
You can get a build with the fix from http://ci.codecrafter47.dyndns.eu/job/BungeeTabListPlus/
