### ISSUE TITLE
Connection timed out when checking for new dev-build.

### ISSUE THREAD

**Issue by BrainStone** [CodeCrafter47/BungeeTabListPlus#245]
It appears that the website to check for updates is currently down. Which is not the issue I'm trying to report. But rather that this error pointlessly spams my console every so often. There really is no point in printing the stacktrace.

So instead of:

```
13:11:36 [WARNUNG] [BungeeTabListPlus] Failed to check whether a new dev-build is available.
java.net.ConnectException: Die Wartezeit für die Verbindung ist abgelaufen (Connection timed out)
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at java.net.Socket.connect(Socket.java:538)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
    at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
    at sun.net.www.http.HttpClient.New(HttpClient.java:339)
    at sun.net.www.http.HttpClient.New(HttpClient.java:357)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
    at java.net.URL.openStream(URL.java:1045)
    at codecrafter47.bungeetablistplus.updater.UpdateChecker.run(UpdateChecker.java:106)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
```

```
13:11:36 [WARNUNG] [BungeeTabListPlus] Failed to check whether a new dev-build is available.
13:11:36 [WARNUNG] [BungeeTabListPlus] java.net.ConnectException: Die Wartezeit für die Verbindung ist abgelaufen (Connection timed out)
```

would suffice! Or add a flag or counter so that the stacktrace is only printed once.

Thanks!

(Please excuse the error message not being in English. My server uses the German locale)

**Comment by CodeCrafter47** [comment]
I changed it not to print an error at all because that's the _normal_ behavior when not using a dev-build.

**Comment by BrainStone** [comment]
Alright. I guess I'll pull the latest dev from the CI then. Thanks.

**Comment by CodeCrafter47** [comment]
Unfortunately that's currently offline.

**Comment by BrainStone** [comment]
Ah. Ok. Then I'll have to wait. I'm glad knowing that it is fixed though.

**Comment by CodeCrafter47** [comment]
Jenkins is back online, you can now get the latest build there.
