### ISSUE TITLE
Bug with basic configuration of BungeeTabListPlus

### ISSUE THREAD

**Issue by NyCoSD** [CodeCrafter47/BungeeTabListPlus#246]
Hey,

I had a problem with my configuration after your last update, thinking of a possible modification in the file default.yml, I deleted my configurations, even with the default configuration here is the error code identical to the one I ' Had previously:

Sorry but all code isn't cointains in code quote...

` 10:33:46 [WARNING] [BungeeTabListPlus] Failed to load default.yml
Cannot create property=customPlaceholders for JavaBean=codecrafter47.bungeetablistplus.config.FixedSizeConfig@1280851e
 in 'reader', line 16, column 1:
    showTo: "all"
    ^
Can't construct a java object for tag:yaml.org,2002:codecrafter47.bungeetablistplus.config.CustomPlaceholder$Conditional; exception=java.lang.Boolean cannot be cast to java.lang.String
 in 'reader', line 65, column 5:
        !conditional
        ^

 in 'reader', line 64, column 3:
      afk_tag:
      ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:313)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:190)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:184)
	at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:218)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:143)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:129)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:505)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:465)
	at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig.read(YamlConfig.java:79)
	at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig.read(YamlConfig.java:75)
	at codecrafter47.bungeetablistplus.managers.TabListManager.loadTabLists(TabListManager.java:80)
	at codecrafter47.bungeetablistplus.BungeeTabListPlus.onEnable(BungeeTabListPlus.java:368)
	at codecrafter47.bungeetablistplus.BungeePlugin.onEnable(BungeePlugin.java:40)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:273)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: Can't construct a java object for tag:yaml.org,2002:codecrafter47.bungeetablistplus.config.CustomPlaceholder$Conditional; exception=java.lang.Boolean cannot be cast to java.lang.String
 in 'reader', line 65, column 5:
        !conditional
        ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:350)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:184)
	at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:218)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:376)
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:185)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:357)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:171)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:184)
	at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:218)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:298)
	... 16 more
Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:239)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:190)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:346)
	... 25 more `

Thancks for advance <3

**Comment by CodeCrafter47** [comment]
Which version of BungeeTabListPlus and which version of BungeeCord are you using?

**Comment by NyCoSD** [comment]
I have a last version of Bungeecord (Date:  and

**Comment by NyCoSD** [comment]
I have a last version of Bungeecors(#1250 (
7 juil. 2017 05:12:10) and for btlp I have 2.8.0 version

**Comment by CodeCrafter47** [comment]
I just tested it and using build 1250 of BungeeCord and version 2.8.0 of BungeeTabListPlus loads the default.yml just fine.

However the issue you encountered will occur when using an older version of BungeeTabListPlus (2.7.3 and older) with a recent version of BungeeCord. I recommend you double check the BungeeCord and plugin version you use.

**Comment by NyCoSD** [comment]
I reinitialized my bungee and it seems to work. Thank you all the same !
