### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RaitMan** [CodeCrafter47/BungeeTabListPlus#248]
I have this error

Cannot create property=components for JavaBean=codecrafter47.bungeetablistplus.config.FixedSizeConfig@48e1f6c7
 in 'reader', line 1, column 1:
    showTo: "all"
    ^
Cannot create property=columns for JavaBean=codecrafter47.bungeetablistplus.config.components.PlayersByServerComponent@4722ef0c
 in 'reader', line 60, column 3:
    - !players_by_server
      ^
Unable to find property 'columns' on class: codecrafter47.bungeetablistplus.config.components.PlayersByServerComponent
 in 'reader', line 62, column 5:
        0:
        ^

 in 'reader', line 60, column 1:
    - !players_by_server
    ^

    at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:313)
    at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:190)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:184)
    at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:239)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:143)
    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:129)
    at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:505)
    at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:465)
    at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig.read(YamlConfig.java:100)
    at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig.read(YamlConfig.java:96)
    at codecrafter47.bungeetablistplus.managers.TabListManager.loadTabLists(TabListManager.java:67)
    at codecrafter47.bungeetablistplus.BungeeTabListPlus.onEnable(BungeeTabListPlus.java:371)
    at codecrafter47.bungeetablistplus.BungeePlugin.onEnable(BungeePlugin.java:40)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:273)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: Cannot create property=columns for JavaBean=codecrafter47.bungeetablistplus.config.components.PlayersByServerComponent@4722ef0c
 in 'reader', line 60, column 3:
    - !players_by_server
      ^
Unable to find property 'columns' on class: codecrafter47.bungeetablistplus.config.components.PlayersByServerComponent
 in 'reader', line 62, column 5:
        0:
        ^

    at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:313)
    at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:190)
    at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:346)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:184)
    at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:239)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2(BaseConstructor.java:277)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequence(BaseConstructor.java:248)
    at org.yaml.snakeyaml.constructor.Constructor$ConstructSequence.construct(Constructor.java:539)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:184)
    at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:239)
    at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:298)
    ... 16 more
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'columns' on class: codecrafter47.bungeetablistplus.config.components.PlayersByServerComponent
    at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:132)
    at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:121)
    at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:323)
    at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:241)
    ... 26 more

AND MY CONFIG IS THIS!
----------------------------

showTo: "all"

priority: 22

type: FIXED_SIZE

showHeaderFooter: true

header:
- '&8&l[&3&l&m--&8&l{&3&l&m-&8&l[ &3&lBluestone Network &8&l]&3&l&m-&8&l}&3&l&m--&8&l]'

headerAnimationUpdateInterval: 0.2

footer:
- |-
  &3&l> &8&lFoorum &7www.swag.com/1337
  &3&l> &8&lMuu &7Midagi veel.
- |-
  &3&l> &8&lFoorum &7www.swag.com/1337
  &3&l> &8&lMuu &7Midagi veel.
  
footerAnimationUpdateInterval: 0.5

customPlaceholders:
  afk_tag:
    !conditional
    condition: ${player essentials_afk}
    true: '&7|&oaway'
    false: ''
  viewer_colored_ping0:
    !conditional
    condition: "${viewer ping} < 50"
    true: "&a${viewer ping}"
    false: "&e${viewer ping}"
  viewer_colored_ping:
    !conditional
    condition: "${viewer ping} < 150"
    true: ${viewer_colored_ping0}
    false: "&c${viewer ping}"

defaultIcon: colors/dark_gray.png
defaultPing: 1000
size: 80
playerSets:
  global:
    filter: "true"
  lobby:
    filter: |-
      ${player server} == "lobby"
  survival:
    filter: |-
      ${player server} == "survival"
  pvp:
    filter: |-
      ${player server} == "pvp"
  event:
    filter: |-
      ${player server} == "event"
components:
- !players_by_server
  columns:
    0:
      - {text: "&7&lServer &3&l> &6${viewer server}", icon: "colors/dark_gray.png", ping: 0}
      - {text: "", icon: "colors/dark_gray.png", ping: 1000}
      - {text: "&7&lHub", icon: "colors/dark_green.png", ping: 0}
      - !players
        playerSet: hub
        playerComponent: {text: "${player name}${afk_tag}", icon: "${player skin}", ping: "${player ping}"}
        morePlayersComponent: {text: "&7... ja &e${other_count} &7veel", icon: "colors/gray.png", ping: 0}
    1:
      - {text: "&7&lRank &3&l> &6${viewer vault_primary_group}", icon: "colors/dark_gray.png", ping: 0}
      - {text: "", icon: "colors/dark_gray.png", ping: 1000}
      - {text: "&3&lSurvival", icon: "colors/dark_aqua.png", ping: 0}
      - !players
        playerSet: survival
        playerComponent: {text: "${player name}${afk_tag}", icon: "${player skin}", ping: "${player ping}"}
        morePlayersComponent: {text: "&7... ja &e${other_count} &7veel", icon: "colors/dark_aqua.png", ping: 0}
    2:
      - {text: "&7&lPing &3&l> ${viewer_colored_ping}ms", icon: "colors/dark_gray.png", ping: 0}
      - {text: "", icon: "colors/dark_gray.png", ping: 1000}
      - {text: "&8&lCreative", icon: "colors/gray.png", ping: 0}
      - !players
        playerSet: creative
        playerComponent: {text: "${player name}${afk_tag}", icon: "${player skin}", ping: "${player ping}"}
        morePlayersComponent: {text: "&7... ja &e${other_count} &7veel", icon: "colors/dark_gray.png", ping: 0}
    3:
      - {text: "&7/lKokku &3&l> &7&l{playerset:global size}", icon: "colors/gray.png", ping: 0}
      - {text: "", icon: "colors/dark_gray.png", ping: 1000}
      - {text: "&e&lEvent", icon: "colors/yellow.png", ping: 0}     
      - !players      
        playerSet: event
        playerComponent: {text: "${player name}${afk_tag}", icon: "${player skin}", ping: "${player ping}"}
        morePlayersComponent: {text: "&7... ja &e${other_count} &7veel", icon: "colors/dark_gray.png", ping: 0}

**Comment by CodeCrafter47** [comment]
To use the table component use `!table` not `!players_by_server`. You can find more information about using the table component on the following wiki page: https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Configuration-Basics-Part-8---Fixed-Size-Tablist---Table

**Comment by RaitMan** [comment]
Now i have 1 error.


23:53:43 [WARNING] [BungeeTabListPlus] Failed to load default.yml
while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 43, column 59:
     ... lors/dark_gray.png", ping: 1000}
                                         ^

    at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:420)
    at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
    at org.yaml.snakeyaml.parser.ParserImpl$ParseIndentlessSequenceEntry.produce(ParserImpl.java:531)
    at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
    at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147)
    at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:198)
    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:152)
    at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246)
    at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237)
    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225)
    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
    at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246)
    at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237)
    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225)
    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
    at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:199)
    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:152)
    at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246)
    at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237)
    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225)
    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
    at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
    at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:122)
    at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:505)
    at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:465)
    at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig.read(YamlConfig.java:100)
    at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig.read(YamlConfig.java:96)
    at codecrafter47.bungeetablistplus.managers.TabListManager.loadTabLists(TabListManager.java:67)
    at codecrafter47.bungeetablistplus.BungeeTabListPlus.onEnable(BungeeTabListPlus.java:371)
    at codecrafter47.bungeetablistplus.BungeePlugin.onEnable(BungeePlugin.java:40)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:273)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by CodeCrafter47** [comment]
As the error message says you cannot use tabs, you must use spaces instead.
