### ISSUE TITLE
Weird error code.

### ISSUE THREAD

**Issue by roopekoo** [CodeCrafter47/BungeeTabListPlus#25]
@CodeCrafter47 
I got this weird error code about every 15 minutes:

14:50:15 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@14008db3, id=3, owner=codecrafter47.bungeetablistplus.BungeeTabListPlus@7f284218, task=codecrafter47.bungeetablistplus.Metrics$1@398dada8, delay=0, period=900000, running=true) encountered an exception
java.lang.NullPointerException
	at codecrafter47.bungeetablistplus.Metrics.appendJSONPair(Metrics.java:563)
	at codecrafter47.bungeetablistplus.Metrics.postPlugin(Metrics.java:367)
	at codecrafter47.bungeetablistplus.Metrics.access$400(Metrics.java:45)
	at codecrafter47.bungeetablistplus.Metrics$1.run(Metrics.java:237)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by CodeCrafter47** [comment]
You have most likely edited plugins/PluginMetrics/config.properties. You shouldn't do that. The error should disappear if you remove the file.

**Comment by roopekoo** [comment]
@CodeCrafter47 
Nope! I removed plugins/PluginMetrics/config.properties and I still get that same error at bungee server start up and then every time precisely 15 minutes later.

**Comment by CodeCrafter47** [comment]
That's strange.

This error doesn't happen to me, but your not the only one having this error, so it is probably related to some other plugin or a specific bungee version.

**Comment by roopekoo** [comment]
BungeeCord version: git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"fa828eb":1059
Plugins:
BungeeChatPlus-0.6.1
BungeeTabListPlus-2.0#4
BungeeYAML 1.2.5
