### ISSUE TITLE
Unable to prepare head

### ISSUE THREAD

**Issue by Coolfeather2** [CodeCrafter47/BungeeTabListPlus#264]
```
18:44:57 [WARNING] [BungeeTabListPlus] An error occurred while trying to contact skinservice.codecrafter47.dyndns.eu
java.io.IOException: Server returned HTTP response code: 503 for URL: http://skinservice.codecrafter47.dyndns.eu/api/customhead
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1466)
at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1464)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1463)
at codecrafter47.bungeetablistplus.managers.SkinManagerImpl.fetchHeadSkin(SkinManagerImpl.java:182)
at codecrafter47.bungeetablistplus.managers.SkinManagerImpl.lambda$getSkin$3(SkinManagerImpl.java:158)
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```
```
18:44:57 [WARNING] [BungeeTabListPlus] Unable to prepare head players.png
```

**Comment by CodeCrafter47** [comment]
The service is back online now. Your custom icons should be working now.

**Comment by Coolfeather2** [comment]
Thanks, keep up the hard work!
