### ISSUE TITLE
Problem with Spigot Essentials snapshot

### ISSUE THREAD

**Issue by Lahemees47** [CodeCrafter47/BungeeTabListPlus#27]
This error is spamming my console:

[18:44:19 WARN]: [BungeeTabListPlus_BukkitBridge] §cAn internal error occured! Please send the following stacktrace to the developer in order to help resolving the problem
java.lang.RuntimeException: Essentials API is called before Essentials is loaded.
        at com.earth2me.essentials.api.Economy.getUserByName(Economy.java:80) ~[Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.api.Economy.getMoneyExact(Economy.java:104) ~[Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.api.Economy.getMoney(Economy.java:99) ~[Essentials-2.x-SNAPSHOT.jar:?]
        at net.milkbowl.vault.economy.plugins.Economy_Essentials.getBalance(Economy_Essentials.java:78) ~[Vault.jar:?]
        at codecrafter47.bungeetablistplus.bukkitbridge.informationhooks.VaultHook.getInformation(VaultHook.java:110) [BungeeTabListPlus_BukkitBridge-7.jar:?]
        at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.update(PlayerInformationUpdateTask.java:95) [BungeeTabListPlus_BukkitBridge-7.jar:?]
        at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.run(PlayerInformationUpdateTask.java:61) [BungeeTabListPlus_BukkitBridge-7.jar:?]
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-b38b33e-1e56438]
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-Spigot-b38b33e-1e56438]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0]
        at java.lang.Thread.run(Thread.java:744) [?:1.8.0]

**Comment by CodeCrafter47** [comment]
Probably Essentials didn't load properly. Maybe there's an error in its configuration.

**Comment by Lahemees47** [comment]
Yup, downgraded Essentials Spigot back to #10 from #12 and it's working again.
