### ISSUE TITLE
Luckperm is updated but not this plugin is broken

### ISSUE THREAD

**Issue by andsim** [CodeCrafter47/BungeeTabListPlus#314]
[BungeeTabListPlus] Failed to acquire data DataKey(id=luckperms:prefix, scope=Scope(id=bungee:player), type=de.codecrafter47.data.api.TypeToken@1ab6718, parameter=null) from andsim
Console 01/30/2018 19:08:02
19:08:02java.lang.NoSuchMethodError: me.lucko.luckperms.api.User.getUserDataCache()Ljava/util/Optional;
at de.codecrafter47.data.bungee.luckperms.LuckPermsPrefixProvider.apply(LuckPermsPrefixProvider.java:43)
at de.codecrafter47.data.bungee.luckperms.LuckPermsPrefixProvider.apply(LuckPermsPrefixProvider.java:29)
at de.codecrafter47.data.api.AbstractDataAccess.lambda$addProvider$0(AbstractDataAccess.java:30)
at de.codecrafter47.data.api.AbstractDataAccess.get(AbstractDataAccess.java:44)
at de.codecrafter47.data.bungee.AbstractBungeeDataAccess.get(AbstractBungeeDataAccess.java:42)
at de.codecrafter47.data.api.JoinedDataAccess.get(JoinedDataAccess.java:40)
at codecrafter47.bungeetablistplus.managers.DataManager.updateData(DataManager.java:71)
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by CodeCrafter47** [comment]
Get the latest dev-builf of BungeeTabListPlus from <https://ci.codecrafter47.de/job/BungeeTabListPlus/>. This issue has been fixed months ago.

**Comment by Seeroh** [comment]
I get time-out errors when trying to load the jenkins. So I can't access a dev build, to stop the spam.
