### ISSUE TITLE
Error in Bungeecord console, using version 2.0#5-SNAPSHOT

### ISSUE THREAD

**Issue by Lahemees47** [CodeCrafter47/BungeeTabListPlus#32]
20:53:21 [WARNING] [BungeeTabListPlus] An internal error occurred! Please send the following StackTrace to the developer in order to help resolving the problem
java.net.ConnectException: Connection timed out
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:649)
    at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
    at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1103)
    at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:987)
    at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:985)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessController.doPrivileged(AccessController.java:713)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:984)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
    at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1281)
    at sun.net.www.protocol.http.HttpURLConnection.access$100(HttpURLConnection.java:90)
    at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1248)
    at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1246)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessController.doPrivileged(AccessController.java:713)
    at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1245)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
    at codecrafter47.bungeetablistplus.managers.SkinManager.fetchUUID(SkinManager.java:81)
    at codecrafter47.bungeetablistplus.managers.SkinManager.access$400(SkinManager.java:45)
    at codecrafter47.bungeetablistplus.managers.SkinManager$SkinFetchTask.run(SkinManager.java:165)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:744)

**Comment by CodeCrafter47** [comment]
Somehow the plugin couldn't connect to mojang servers.

**Comment by Lahemees47** [comment]
Maybe you could replace the stacktrace with "Error: Couldn't connect to Mojang servers." or something like that ;)

**Comment by CodeCrafter47** [comment]
Yeah I think I will change that error message.

It connects to mojang servers to get the skins used for the heads in the tablist.

**Comment by Lahemees47** [comment]
Thanks. Oh yeah, forgot about the heads.
