### ISSUE TITLE
Sponge Bridge Spam Error LuckPerms service

### ISSUE THREAD

**Issue by Yann151924** [CodeCrafter47/BungeeTabListPlus#325]
I have this error on my server, when i swtich off the bridge i don't have it anymore. This a the first of the error : 
`28.02 23:02:31 [Server] pool-2-thread-17/ERROR [bungeetablistplus]: Unexpected exception
28.02 23:02:31 [Server] INFO java.lang.ClassCastException: me.lucko.luckperms.sponge.service.reference.LuckPermsSubjectReference cannot be cast to org.spongepowered.api.service.permission.Subject`

**Comment by CodeCrafter47** [comment]
Full stack trace, please.

**Comment by Yann151924** [comment]
`[14:54:32] [pool-2-thread-8/ERROR] [bungeetablistplus]: Unexpected exception
java.lang.ClassCastException: me.lucko.luckperms.sponge.service.reference.LuckPermsSubjectReference cannot be cast to org.spongepowered.api.service.permission.Subject
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_161]
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[?:1.8.0_161]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_161]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[?:1.8.0_161]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:1.8.0_161]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_161]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_161]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_161]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[?:1.8.0_161]
	at de.codecrafter47.data.sponge.sponge5.Sponge5.getPrimaryGroup(Sponge5.java:26) ~[Sponge5.class:?]
	at de.codecrafter47.data.api.AbstractDataAccess.lambda$addProvider$0(AbstractDataAccess.java:30) ~[AbstractDataAccess.class:?]
	at de.codecrafter47.data.api.AbstractDataAccess.get(AbstractDataAccess.java:44) ~[AbstractDataAccess.class:?]
	at de.codecrafter47.data.sponge.AbstractSpongeDataAccess.get(AbstractSpongeDataAccess.java:35) ~[AbstractSpongeDataAccess.class:?]
	at de.codecrafter47.data.api.JoinedDataAccess.get(JoinedDataAccess.java:40) ~[JoinedDataAccess.class:?]
	at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updatePlayerData(AbstractBridge.java:381) ~[AbstractBridge.class:?]
	at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updateData(AbstractBridge.java:316) ~[AbstractBridge.class:?]
	at codecrafter47.bungeetablistplus.spongebridge.SpongePlugin.lambda$onServerStart$3(SpongePlugin.java:146) ~[SpongePlugin.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2611-7.1.0-BETA-2953]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-2611-7.1.0-BETA-2953]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
`

This is the full stack trace

**Comment by CodeCrafter47** [comment]
What are the exact versions of Sponge and LuckPerms you are using? Are you sure they are compatible.

**Comment by Yann151924** [comment]
Sorry for the very very late response but i don't have anymore this error.
