### ISSUE TITLE
Support for FactionsUUID (Faction 1.8.2 and 1.6.9.5)

### ISSUE THREAD

**Issue by sgdc3** [CodeCrafter47/BungeeTabListPlus#33]

**Comment by sgdc3** [comment]
Error when using FactionsUUID:
```
[BungeeTabListPlus_BukkitBridge] An internal error occured! Please send the following stacktrace to the developer in order to help resolving the problem
java.lang.NoClassDefFoundError: com/massivecraft/factions/entity/MPlayer
    at codecrafter47.bungeetablistplus.bukkitbridge.informationhooks.FactionHook_7_3_0.getInformation(FactionHook_7_3_0.java:42) ~[BungeeTabListPlus_BukkitBridge-7.jar:?]
    at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.init(PlayerInformationUpdateTask.java:75) [BungeeTabListPlus_BukkitBridge-7.jar:?]
    at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.run(PlayerInformationUpdateTask.java:59) [BungeeTabListPlus_BukkitBridge-7.jar:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [pspigot185.jar:git-PaperSpigot-ebb90ce-529e4cd]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [pspigot185.jar:git-PaperSpigot-ebb90ce-529e4cd]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_45]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.entity.MPlayer
    at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_45]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[pspigot185.jar:git-PaperSpigot-ebb90ce-529e4cd]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[pspigot185.jar:git-PaperSpigot-ebb90ce-529e4cd]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
    ... 8 more
```

**Comment by CodeCrafter47** [comment]
FactionsUUID support has been added. If you want to test it grab the latest dev-build. A release will follow soon.
