### ISSUE TITLE
cannot load default.yml

### ISSUE THREAD

**Issue by achencraft** [CodeCrafter47/BungeeTabListPlus#333]
hey, when I launch the server, I have this error

`
at java.lang.Thread.run(Thread.java:745)
--
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
at codecrafter47.bungeetablistplus.ResendThread.run(ResendThread.java:101)
at codecrafter47.bungeetablistplus.BungeeTabListPlus.lambda$reload$2(BungeeTabListPlus.java:409)
at codecrafter47.bungeetablistplus.BungeeTabListPlus.reload(BungeeTabListPlus.java:444)
at codecrafter47.bungeetablistplus.BungeeTabListPlus.reloadTablists(BungeeTabListPlus.java:459)
at codecrafter47.bungeetablistplus.managers.TabListManager.loadTabLists(TabListManager.java:67)
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to codecrafter47.bungeetablistplus.config.ITabListConfig
21:02:18 [WARNING] [BungeeTabListPlus] Failed to load default.yml

`
We need to read from bottom to top

someone have an idea ?

**Comment by CodeCrafter47** [comment]
Probably you're not using the latest version of the plugin.

**Comment by achencraft** [comment]
I'm using the 2.8.3.
This is the latest, no ?

**Comment by CodeCrafter47** [comment]
Yes, that's the latest.

In that case the issue is probably in the config file (you edited it?).

**Comment by achencraft** [comment]
Hum, I don't think.

You can look files here : http://achencraft.fr/temporaire/bungeetablistplus/

**Comment by CodeCrafter47** [comment]
Your config file has been created by a very old version of the plugin. It is no longer compatible with the latest version of the plugin. You should delete the config files and let the plugin create new ones.

**Comment by achencraft** [comment]
ok, I did it and I have the new config file.
Now, another error :'(

`18:15:58 [INFO] Enabled plugin BungeeTabListPlus version 2.8.3 by CodeCrafter47
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:273)
at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
at codecrafter47.bungeetablistplus.BungeePlugin.onEnable(BungeePlugin.java:40)
at codecrafter47.bungeetablistplus.BungeeTabListPlus.onEnable(BungeeTabListPlus.java:374)
at codecrafter47.bungeetablistplus.managers.TabListManager.loadTabLists(TabListManager.java:67)
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to codecrafter47.bungeetablistplus.config.ITabListConfig
18:15:58 [WARNING] [BungeeTabListPlus] Failed to load default.yml
18:15:58 [INFO] [BungeeTabListPlus] Loading default.yml`

**Comment by CodeCrafter47** [comment]
I'd say you didn't change anything, cause the error message still looks the same.

**Comment by achencraft** [comment]
sorry, I put the old config on the webserver
I'm changing it now
I have restarted bungeecord, but the error is the same

Do you think that the Motd can create this bug, because it's the only thing i've changed before errors.

**Comment by CodeCrafter47** [comment]
You can try removing the Modt to find out.

Though if the error is the same, chances are you're still using the old config.
