### ISSUE TITLE
[WARNING] [BungeeTabListPlus] An internal error occurred! Please send the following StackTrace to the developer in order to help resolving the problem

### ISSUE THREAD

**Issue by nflug** [CodeCrafter47/BungeeTabListPlus#34]
java.lang.NullPointerException
    at codecrafter47.bungeetablistplus.managers.PermissionManager.getPrefix(PermissionManager.java:169)
    at codecrafter47.bungeetablistplus.variables.PermPrefix.getReplacement(PermPrefix.java:35)
    at codecrafter47.bungeetablistplus.managers.VariablesManager.replacePlayerVariables(VariablesManager.java:165)
    at codecrafter47.bungeetablistplus.section.FillPlayersSection.drawPlayerLines(FillPlayersSection.java:154)
    at codecrafter47.bungeetablistplus.section.FillPlayersSection.calculate(FillPlayersSection.java:141)
    at codecrafter47.bungeetablistplus.config.TabListProvider.fillTabList(TabListProvider.java:293)
    at codecrafter47.bungeetablistplus.ResendThread.update(ResendThread.java:111)
    at codecrafter47.bungeetablistplus.ResendThread.run(ResendThread.java:66)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

MfG nflug
Email: patrickdeschauer@gmail.com

**Comment by CodeCrafter47** [comment]
Does this problem still occur in the latest dev-build?
