### ISSUE TITLE
Custom Head Problems

### ISSUE THREAD

**Issue by BijuuKrunos** [CodeCrafter47/BungeeTabListPlus#346]
Hey guys,

i have a problem with self maded heads.
I created own heads.png for my tablist and put them in my tablists. The heads are all 8x8 and converted in .png but my Log get spamed by this errors:

`[18:34:52] [BungeeTabListPlus Pool Thread #56/INFO] [BungeeTabListPlus]: Preparing head TPS.png approx. 1.0 minutes remaining.
[18:34:52] [BungeeTabListPlus Pool Thread #50/INFO] [BungeeTabListPlus]: Preparing head Players.png approx. 3.0 minutes remaining.
[18:34:52] [BungeeTabListPlus Pool Thread #57/INFO] [BungeeTabListPlus]: Preparing head Time.png approx. 4.0 minutes remaining.
[18:34:52] [BungeeTabListPlus Pool Thread #58/INFO] [BungeeTabListPlus]: Preparing head Players.png approx. 3.0 minutes remaining.
[18:34:52] [BungeeTabListPlus Pool Thread #52/INFO] [BungeeTabListPlus]: Preparing head Ping.png approx. 1.0 minutes remaining.
[18:34:52] [BungeeTabListPlus Pool Thread #51/INFO] [BungeeTabListPlus]: Preparing head Area.png approx. 2.0 minutes remaining.
[18:34:52] [BungeeTabListPlus Pool Thread #53/INFO] [BungeeTabListPlus]: Preparing head Rank.png approx. 5.0 minutes remaining.
`

i hope you can help me. 

Greetz Krunos

**Comment by CodeCrafter47** [comment]
I'm looking into it.

**Comment by CodeCrafter47** [comment]
I made a quick fix, i.e. if you do `/btlp reload` now it should fetch your icons correctly. Don't know how stable it is though. I'll be working on a more permanent fix.

**Comment by BijuuKrunos** [comment]
okey after i reloaded a few times i got this error:

`[17:22:45] [BungeeTabListPlus Pool Thread #5297/WARN] [BungeeTabListPlus]: Unable to prepare head tps.png
[17:22:45] [BungeeTabListPlus Pool Thread #640/WARN] [BungeeTabListPlus]: An error occurred while trying to contact skinservice.codecrafter47.dyndns.eu
java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:400) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:243) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:225) ~[?:?]
        at java.net.Socket.connect(Socket.java:591) ~[?:?]
        at java.net.Socket.connect(Socket.java:540) ~[?:?]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:182) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:569) ~[?:?]
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:?]
        at sun.net.www.http.HttpClient.New(HttpClient.java:341) ~[?:?]
        at sun.net.www.http.HttpClient.New(HttpClient.java:362) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1242) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1075) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1009) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1356) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1331) ~[?:?]
        at codecrafter47.bungeetablistplus.managers.SkinManagerImpl.fetchHeadSkin(SkinManagerImpl.java:178) ~[?:?]
        at codecrafter47.bungeetablistplus.managers.SkinManagerImpl.lambda$fetchHeadSkin$4(SkinManagerImpl.java:189) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:7aa12d5:174]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) [?:?]
        at java.lang.Thread.run(Thread.java:844) [?:?]
`


i got this

`[17:22:45] [BungeeTabListPlus Pool Thread #3058/WARN] [BungeeTabListPlus]: Unable to prepare head players.png
[17:22:45] [BungeeTabListPlus Pool Thread #9487/WARN] [BungeeTabListPlus]: Unable to prepare head tps.png
[17:22:45] [BungeeTabListPlus Pool Thread #7964/WARN] [BungeeTabListPlus]: Unable to prepare head players.png
[17:22:45] [BungeeTabListPlus Pool Thread #858/WARN] [BungeeTabListPlus]: Unable to prepare head tps.png
[17:22:45] [BungeeTabListPlus Pool Thread #859/WARN] [BungeeTabListPlus]: Unable to prepare head area.png
[17:22:45] [BungeeTabListPlus Pool Thread #5308/WARN] [BungeeTabListPlus]: Unable to prepare head tps.png
[17:22:45] [BungeeTabListPlus Pool Thread #5034/WARN] [BungeeTabListPlus]: Unable to prepare head tps.png
[17:22:45] [BungeeTabListPlus Pool Thread #3127/WARN] [BungeeTabListPlus]: Unable to prepare head tps.png
[17:22:45] [BungeeTabListPlus Pool Thread #7890/WARN] [BungeeTabListPlus]: Unable to prepare head area.png
[17:22:45] [BungeeTabListPlus Pool Thread #640/WARN] [BungeeTabListPlus]: Unable to prepare head area.png
[17:22:45] [BungeeTabListPlus Pool Thread #5300/WARN] [BungeeTabListPlus]: Unable to prepare head tps.png
[17:22:45] [BungeeTabListPlus Pool Thread #857/WARN] [BungeeTabListPlus]: Unable to prepare head area.png
[17:22:45] [BungeeTabListPlus Pool Thread #7891/WARN] [BungeeTabListPlus]: Unable to prepare head area.png
`


than after another reload:

`[17:23:02] [Console Command Thread #0/INFO]: CONSOLE executed command: /btlp reload
[17:23:02] [BungeeTabListPlus Pool Thread #10/INFO] [BungeeTabListPlus]: Loading HBMC1.0.yml
[17:23:02] [BungeeTabListPlus Pool Thread #10/INFO] [BungeeTabListPlus]: Loading teamHBMC1.0.yml
[17:23:02] [Console Command Thread #0/INFO]: Successfully reloaded BungeeTabListPlus.
[17:23:45] [Netty Worker IO Thread #15/INFO]: [/31.18.40.213:52372] <-> InitialHandler has connected
[17:23:46] [Netty Worker IO Thread #15/INFO]: [BijuuKrunos|/31.18.40.213:52372] <-> ServerConnector [Spawn] has connected
[17:23:47] [BungeeTabListPlus Pool Thread #3071/WARN] [BungeeTabListPlus]: Requested file does not exists: /home/Minecraft/Netzwerk/Bungeecord/plugins/BungeeTabListPlus/heads/area.png
[17:23:47] [BungeeTabListPlus Pool Thread #3071/WARN] [BungeeTabListPlus]: Requested file does not exists: /home/Minecraft/Netzwerk/Bungeecord/plugins/BungeeTabListPlus/heads/ping.png
`


Now i dont have this 100 Errors per sec anymore and i can see my Images ingame yeah.

Hope it will help you to improve this feature to make it more stable.

thx for your help.

Greetz Krunos
