### ISSUE TITLE
Not compatible with plugin ProtocolSupport and Bungee proxyprotocol

### ISSUE THREAD

**Issue by LoveFrea** [CodeCrafter47/BungeeTabListPlus#364]
I'm using the plugin [ProtocolSupport](https://www.spigotmc.org/resources/protocolsupportbungee.8733/) and both enabled the proxyprotocol support feature in config.yml of BungeeCord
the [BungeeTabListPlus](https://ci.codecrafter47.de/job/BungeeTabListPlus/733/) will report errors and stop work
`[09:52:51 ERROR] [BungeeTabListPlus]: An internal error occurred! Please send the following StackTrace to the developer in order to help resolving the problem
java.lang.IllegalArgumentException: Can't compare unknown protocol type
        at protocolsupport.libs.org.apache.commons.lang3.Validate.isTrue(Validate.java:156) ~[ProtocolSupportBungee.jar:?]
        at protocolsupport.api.ProtocolVersion$OrderId.compareTo(ProtocolVersion.java:372) ~[ProtocolSupportBungee.jar:?]
        at protocolsupport.api.ProtocolVersion.isAfterOrEq(ProtocolVersion.java:129) ~[ProtocolSupportBungee.jar:?]
        at codecrafter47.bungeetablistplus.version.ProtocolSupportVersionProvider.has18OrLater(ProtocolSupportVersionProvider.java:42) ~[BungeeTabListPlus-2.8.5-SNAPSHOT.jar:?]
        at codecrafter47.bungeetablistplus.player.ConnectedPlayer.createTabListHandler(ConnectedPlayer.java:106) ~[BungeeTabListPlus-2.8.5-SNAPSHOT.jar:?]
        at codecrafter47.bungeetablistplus.player.ConnectedPlayer.getPlayerTablistHandler(ConnectedPlayer.java:99) ~[BungeeTabListPlus-2.8.5-SNAPSHOT.jar:?]
        at codecrafter47.bungeetablistplus.ResendThread.update(ResendThread.java:125) ~[BungeeTabListPlus-2.8.5-SNAPSHOT.jar:?]
        at codecrafter47.bungeetablistplus.ResendThread.run(ResendThread.java:110) [BungeeTabListPlus-2.8.5-SNAPSHOT.jar:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_172]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_172]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]`

**Comment by CodeCrafter47** [comment]
Can you check whether the latest dev-build fixes the issue?

**Comment by elstur** [comment]
For the record, This version of bungee (as suggested by protocol support dev) works more ideally and is compatible with BTLP:
https://github.com/HexagonMC/BungeeCord/releases

**Comment by LoveFrea** [comment]
A new problems (Build [#735](https://ci.codecrafter47.de/job/BungeeTabListPlus/735/))
`[23:10:26] [Netty Worker IO Thread #19/ERROR] [BungeeTabListPlus]: An internal error occurred! Please send the following StackTrace to the developer in order to help resolving the problem
java.lang.IllegalArgumentException: Can't compare unknown protocol type
	at protocolsupport.libs.org.apache.commons.lang3.Validate.isTrue(Validate.java:156) ~[ProtocolSupportBungee.jar:?]
	at protocolsupport.api.ProtocolVersion$OrderId.compareTo(ProtocolVersion.java:372) ~[ProtocolSupportBungee.jar:?]
	at protocolsupport.api.ProtocolVersion.isAfterOrEq(ProtocolVersion.java:129) ~[ProtocolSupportBungee.jar:?]
	at codecrafter47.bungeetablistplus.version.ProtocolSupportVersionProvider.has18OrLater(ProtocolSupportVersionProvider.java:42) ~[BungeeTabListPlus-2.8.5-SNAPSHOT.jar:?]
	at codecrafter47.bungeetablistplus.player.ConnectedPlayer.createTabListHandler(ConnectedPlayer.java:104) ~[BungeeTabListPlus-2.8.5-SNAPSHOT.jar:?]
	at codecrafter47.bungeetablistplus.player.ConnectedPlayer.getPacketHandler(ConnectedPlayer.java:92) ~[BungeeTabListPlus-2.8.5-SNAPSHOT.jar:?]
	at codecrafter47.bungeetablistplus.managers.ConnectedPlayerManager.onPlayerDisconnected(ConnectedPlayerManager.java:101) ~[BungeeTabListPlus-2.8.5-SNAPSHOT.jar:?]
	at codecrafter47.bungeetablistplus.listener.TabListListener.onPlayerDisconnect(TabListListener.java:68) [BungeeTabListPlus-2.8.5-SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_172]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:46) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:411) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at net.md_5.bungee.connection.UpstreamBridge.disconnected(UpstreamBridge.java:60) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at net.md_5.bungee.netty.HandlerBoss.channelInactive(HandlerBoss.java:58) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at protocolsupport.protocol.pipeline.common.LogicHandler.channelInactive(LogicHandler.java:50) [ProtocolSupportBungee.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:ea6774c:42]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]`

**Comment by CodeCrafter47** [comment]
Does the plugin work correctly aside of the error in the proxy log?

**Comment by LoveFrea** [comment]
No
