### ISSUE TITLE
Spam in server console ProQuests + PAPI

### ISSUE THREAD

**Issue by weronicamc** [CodeCrafter47/BungeeTabListPlus#367]
Proquest points in the customPlaceholder setings

```
[18:38:26] [Craft Scheduler Thread - 1/WARN]: [BungeeTabListPlus] Failed to query value for placeholder "%proquests_total_points%" from PlaceholderAPI
java.lang.NoClassDefFoundError: me/jacobculley/proquests/ProQuests
	at me.jacobculley.papi.expansion.proquests.ProQuestsExpansion.onPlaceholderRequest(ProQuestsExpansion.java:41) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:342) ~[?:?]
	at codecrafter47.bungeetablistplus.bukkitbridge.placeholderapi.PlaceholderAPIDataAccess.lambda$new$0(PlaceholderAPIDataAccess.java:38) ~[?:?]
	at de.codecrafter47.data.api.AbstractDataAccess.get(AbstractDataAccess.java:44) ~[?:?]
	at de.codecrafter47.data.bukkit.AbstractBukkitDataAccess.get(AbstractBukkitDataAccess.java:43) ~[?:?]
	at de.codecrafter47.data.api.JoinedDataAccess.get(JoinedDataAccess.java:40) ~[?:?]
	at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updatePlayerData(AbstractBridge.java:369) ~[?:?]
	at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updateData(AbstractBridge.java:304) ~[?:?]
	at codecrafter47.bungeetablistplus.bukkitbridge.BukkitBridge.lambda$onEnable$3(BukkitBridge.java:128) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-99c2a37-3819f8d]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-99c2a37-3819f8d]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by CodeCrafter47** [comment]
I'd recommend you to make sure you're using the latest versions of ProRequests and PlaceholderAPI, and also ensure that the ProRequests expansion for PlaceholderAPI is up-to-date.If using the latest versions doesn't fix your issue, you should contact the ProRequests author.
