### ISSUE TITLE
plugin not loading in mc 1.13

### ISSUE THREAD

**Issue by DaveDevil** [CodeCrafter47/BungeeTabListPlus#375]
Spigot server:

Error occurred while enabling BungeeTabListPlus v2.8.5 (Is it up to date?)
java.lang.IllegalArgumentException: Channel must contain : separator
	at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:474) ~[spigot-1.13.jar:git-Spigot-ed1cec9-4e2f571]
	at org.bukkit.plugin.messaging.StandardMessenger.registerOutgoingPluginChannel(StandardMessenger.java:180) ~[spigot-1.13.jar:git-Spigot-ed1cec9-4e2f571]
	at codecrafter47.bungeetablistplus.bukkitbridge.BukkitBridge.onEnable(BukkitBridge.java:104) ~[?:?]
	at codecrafter47.bungeetablistplus.BukkitPlugin.onEnable(BukkitPlugin.java:33) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.jar:git-Spigot-ed1cec9-4e2f571]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.jar:git-Spigot-ed1cec9-4e2f571]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.jar:git-Spigot-ed1cec9-4e2f571]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:424) [spigot-1.13.jar:git-Spigot-ed1cec9-4e2f571]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:338) [spigot-1.13.jar:git-Spigot-ed1cec9-4e2f571]
	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562) [spigot-1.13.jar:git-Spigot-ed1cec9-4e2f571]
	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524) [spigot-1.13.jar:git-Spigot-ed1cec9-4e2f571]
	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423) [spigot-1.13.jar:git-Spigot-ed1cec9-4e2f571]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288) [spigot-1.13.jar:git-Spigot-ed1cec9-4e2f571]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot-1.13.jar:git-Spigot-ed1cec9-4e2f571]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by DaveDevil** [comment]
Also, bungeecord side, I have no errors on console, join with 1.12.x works, but join with 1.13 gives this on client side:

Internal Exception: io.netty.handler.codec.DecoderException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 2 path $

**Comment by danjono** [comment]
My pull request #376 should fix this issue.

**Comment by CodeCrafter47** [comment]
3f6fef8b6240ab0fc89ce8212902f67e08cd0933 fixes the client crash.
