### ISSUE TITLE
Unable to load default file

### ISSUE THREAD

**Issue by Xiazihong** [CodeCrafter47/BungeeTabListPlus#395]
UseBungeeCord:  HexaCord-v148

`12:11:54 [信息] [BungeeTabListPlus] Starting UpdateChecker Task
12:11:54 [信息] [BungeeTabListPlus] Loading default.yml
12:11:55 [警告] [BungeeTabListPlus] Failed to load default.yml
Cannot create property=components for JavaBean=codecrafter47.bungeetablistplus.config.FixedSizeConfig@6048e26a
 in 'reader', line 16, column 1:
    showTo: "all"
    ^
Failed to validate config
 in 'reader', line 167, column 3:
    - !animated # 19th row, 1st column
      ^
com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V

 in 'reader', line 131, column 1:
    - {text: "&cServer: &6${viewer s ... 
    ^

	at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:312)
	at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
	at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
	at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:245)
	at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
	at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
	at codecrafter47.bungeetablistplus.libs.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
	at codecrafter47.bungeetablistplus.libs.snakeyaml.Yaml.loadAs(Yaml.java:410)
	at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig.read(YamlConfig.java:102)
	at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig.read(YamlConfig.java:98)
	at codecrafter47.bungeetablistplus.managers.TabListManager.loadTabLists(TabListManager.java:67)
	at codecrafter47.bungeetablistplus.BungeeTabListPlus.onEnable(BungeeTabListPlus.java:346)
	at codecrafter47.bungeetablistplus.BungeePlugin.onEnable(BungeePlugin.java:40)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:279)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:111)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: Failed to validate config
 in 'reader', line 167, column 3:
    - !animated # 19th row, 1st column
      ^
com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V

	at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:250)
	at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.constructSequenceStep2(BaseConstructor.java:275)
	at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.constructSequence(BaseConstructor.java:246)
	at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.Constructor$ConstructSequence.construct(Constructor.java:536)
	at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
	at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:245)
	at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:297)
	... 16 more
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
	at codecrafter47.bungeetablistplus.config.components.AnimatedComponent.validate(AnimatedComponent.java:70)
	at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:248)
	... 22 more
12:11:55 [信息] Enabled plugin BungeeTabListPlus version 2.8.10-SNAPSHOT by CodeCrafter47`

**Comment by CodeCrafter47** [comment]
The issue here is that BungeeTabListPlus is using an API (`com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V`) that is apparently not available on HexaCord.

However it looks like the issue originates from the use of the `!animated` component, so if you remove these animations from your config it might work fine.

**Comment by Xiazihong** [comment]
> The issue here is that BungeeTabListPlus is using an API (`com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V`) that is apparently not available on HexaCord.
> 
> However it looks like the issue originates from the use of the `!animated` component, so if you remove these animations from your config it might work fine.

New problem

-
`19:07:11 [警告] [BungeeTabListPlus] Failed to load default.yml
Failed to validate config
 in 'reader', line 16, column 1:
    showTo: "true"
    ^
com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;I)V

	at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:250)
	at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
	at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
	at codecrafter47.bungeetablistplus.libs.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
	at codecrafter47.bungeetablistplus.libs.snakeyaml.Yaml.loadAs(Yaml.java:410)
	at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig.read(YamlConfig.java:102)
	at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig.read(YamlConfig.java:98)
	at codecrafter47.bungeetablistplus.managers.TabListManager.loadTabLists(TabListManager.java:67)
	at codecrafter47.bungeetablistplus.BungeeTabListPlus.onEnable(BungeeTabListPlus.java:346)
	at codecrafter47.bungeetablistplus.BungeePlugin.onEnable(BungeePlugin.java:40)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:279)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:111)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;I)V
	at codecrafter47.bungeetablistplus.config.FixedSizeConfig.validate(FixedSizeConfig.java:48)
	at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:248)
	... 13 more`

**Comment by CodeCrafter47** [comment]
That's in one of the core classes of the plugin. So it probably won't run on HexaCord, no matter what you change in the config.

**Comment by Xiazihong** [comment]
> That's in one of the core classes of the plugin. So it probably won't run on HexaCord, no matter what you change in the config.

Ok, thank you for answering

**Comment by Sir-Will** [comment]
@CodeCrafter47 	I'm getting the same error with the 1.7.10 bungee version (build 1119). Isn't the latest version supposed to work for all versions?
```
01:45:53 [INFO] [BungeeTabListPlus] Loading default.yml
01:45:53 [WARNING] [BungeeTabListPlus] Failed to load default.yml
Failed to validate config
 in 'reader', line 13, column 1:
    showTo: "all"
    ^
com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;I)V

    at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:250)
    at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
    at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
    at codecrafter47.bungeetablistplus.libs.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
    at codecrafter47.bungeetablistplus.libs.snakeyaml.Yaml.loadAs(Yaml.java:410)
    at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig.read(YamlConfig.java:102)
    at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig.read(YamlConfig.java:98)
    at codecrafter47.bungeetablistplus.managers.TabListManager.loadTabLists(TabListManager.java:67)
    at codecrafter47.bungeetablistplus.BungeeTabListPlus.onEnable(BungeeTabListPlus.java:343)
    at codecrafter47.bungeetablistplus.BungeePlugin.onEnable(BungeePlugin.java:40)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:256)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;I)V
    at codecrafter47.bungeetablistplus.config.FixedSizeConfig.validate(FixedSizeConfig.java:48)
    at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:248)
    ... 13 more
01:45:53 [INFO] Enabled plugin BungeeTabListPlus version 2.8.11 by CodeCrafter47
```

**Comment by CodeCrafter47** [comment]
BungeeTabListPlus doesn't support BungeeCord build 1119. I don't know which build is the lowest supported version, but the idea is that you use a recent build of BungeeCord.
