### ISSUE TITLE
error spam console

### ISSUE THREAD

**Issue by tonydu51** [CodeCrafter47/BungeeTabListPlus#396]
Hello i having this error spaming my console: (thanks for fix and update)

java.lang.RuntimeException: Exception while querying data from Vault
Vault 1.7.1-b91
Permissions GroupManager GMBuildVer (Phoenix)
	at de.codecrafter47.data.bukkit.vault.VaultDataProvider.apply(VaultDataProvider.java:35) ~[?:?]
	at de.codecrafter47.data.api.AbstractDataAccess.lambda$addProvider$0(AbstractDataAccess.java:30) ~[?:?]
	at de.codecrafter47.data.api.AbstractDataAccess.get(AbstractDataAccess.java:44) ~[?:?]
	at de.codecrafter47.data.bukkit.AbstractBukkitDataAccess.get(AbstractBukkitDataAccess.java:43) ~[?:?]
	at de.codecrafter47.data.api.JoinedDataAccess.get(JoinedDataAccess.java:40) ~[?:?]
	at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updatePlayerData(AbstractBridge.java:369) ~[?:?]
	at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updateData(AbstractBridge.java:304) ~[?:?]
	at codecrafter47.bungeetablistplus.bukkitbridge.BukkitBridge.lambda$onEnable$3(BukkitBridge.java:128) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) [spigot-1.13.jar:git-Spigot-5696c83-1cac9d4]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.jar:git-Spigot-5696c83-1cac9d4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
	at org.anjocaido.groupmanager.dataholder.WorldDataHolder.getUser(WorldDataHolder.java:133) ~[?:?]
	at org.anjocaido.groupmanager.dataholder.OverloadedWorldHolder.getUser(OverloadedWorldHolder.java:53) ~[?:?]
	at org.anjocaido.groupmanager.permissions.AnjoPermissionsHandler.getUserPrefix(AnjoPermissionsHandler.java:335) ~[?:?]
	at net.milkbowl.vault.chat.plugins.Chat_GroupManager.getPlayerPrefix(Chat_GroupManager.java:276) ~[?:?]
	at net.milkbowl.vault.chat.Chat.getPlayerPrefix(Chat.java:67) ~[?:?]
	at net.milkbowl.vault.chat.Chat.getPlayerPrefix(Chat.java:91) ~[?:?]
	at de.codecrafter47.data.bukkit.vault.VaultPrefixProvider.apply0(VaultPrefixProvider.java:31) ~[?:?]
	at de.codecrafter47.data.bukkit.vault.VaultPrefixProvider.apply0(VaultPrefixProvider.java:25) ~[?:?]
	at de.codecrafter47.data.bukkit.vault.VaultDataProvider.apply(VaultDataProvider.java:33) ~[?:?]
	... 12 more

**Comment by CodeCrafter47** [comment]
Your permissions plugin `GroupManager GMBuildVer (Phoenix)` has a bug or is configured incorrectly.
