### ISSUE TITLE
OutOfMemoryError when a player connecting

### ISSUE THREAD

**Issue by jewome62** [CodeCrafter47/BungeeTabListPlus#397]
![image](https://user-images.githubusercontent.com/472429/48980414-d60b7280-f0c8-11e8-9392-1649a1c87b28.png)
All icon are blank but not player

I have tried delete all my conf, to regenerate new config.
I have similar error

![image](https://user-images.githubusercontent.com/472429/48981898-82eeeb00-f0db-11e8-84f3-40995b51718c.png)

```
15:30:04 [INFOS] [jewome62] <-> ServerConnector [Spawn] has connected
15:30:04 [INFOS] [BungeeChat] JOIN > Spawn > jewome62: §ejewome62 has joined the network!
15:30:05 [GRAVE] [BungeeTabListPlus] Error while updating tablist
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1378)
	at net.md_5.bungee.scheduler.BungeeScheduler.schedule(BungeeScheduler.java:104)
	at net.md_5.bungee.scheduler.BungeeScheduler.schedule(BungeeScheduler.java:88)
	at net.md_5.bungee.scheduler.BungeeScheduler.runAsync(BungeeScheduler.java:82)
	at codecrafter47.bungeetablistplus.managers.SkinManagerImpl.getSkin(SkinManagerImpl.java:128)
	at codecrafter47.bungeetablistplus.managers.SkinManagerImpl.getIcon(SkinManagerImpl.java:90)
	at codecrafter47.bungeetablistplus.template.IconTemplate$ConfigIconTemplate.lambda$new$2(IconTemplate.java:61)
	at codecrafter47.bungeetablistplus.template.IconTemplate$ConfigIconTemplate.evaluate(IconTemplate.java:69)
	at codecrafter47.bungeetablistplus.config.components.BasicComponent$Instance.update2ndStep(BasicComponent.java:128)
	at codecrafter47.bungeetablistplus.config.components.ListComponent$Instance.update2ndStep(ListComponent.java:132)
	at codecrafter47.bungeetablistplus.tablistproviders.FixedSizeConfigTablistProvider.update(FixedSizeConfigTablistProvider.java:87)
	at codecrafter47.bungeetablistplus.ResendThread.update(ResendThread.java:148)
	at codecrafter47.bungeetablistplus.ResendThread.run(ResendThread.java:107)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
15:30:05 [GRAVE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@2a265ea9, id=58, owner=codecrafter47.bungeetablistplus.BungeePlugin@f31c0c6, task=codecrafter47.bungeetablistplus.managers.SkinManagerImpl$$Lambda$382/930247557@5d63e995, delay=0, period=0, running=true) encountered an exception
java.lang.NoClassDefFoundError: Could not initialize class sun.java2d.Disposer
	at javax.imageio.stream.FileImageInputStream.<init>(FileImageInputStream.java:98)
	at javax.imageio.stream.FileImageInputStream.<init>(FileImageInputStream.java:73)
	at com.sun.imageio.spi.FileImageInputStreamSpi.createInputStreamInstance(FileImageInputStreamSpi.java:55)
	at javax.imageio.ImageIO.createImageInputStream(ImageIO.java:357)
	at javax.imageio.ImageIO.read(ImageIO.java:1304)
	at codecrafter47.bungeetablistplus.managers.SkinManagerImpl.lambda$getSkin$3(SkinManagerImpl.java:136)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
15:30:05 [GRAVE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@2a265ea9, id=57, owner=codecrafter47.bungeetablistplus.BungeePlugin@f31c0c6, task=codecrafter47.bungeetablistplus.managers.SkinManagerImpl$$Lambda$382/930247557@311f1e0e, delay=0, period=0, running=true) encountered an exception
java.lang.NoClassDefFoundError: Could not initialize class sun.java2d.Disposer
	at javax.imageio.stream.FileImageInputStream.<init>(FileImageInputStream.java:98)
	at javax.imageio.stream.FileImageInputStream.<init>(FileImageInputStream.java:73)
	at com.sun.imageio.spi.FileImageInputStreamSpi.createInputStreamInstance(FileImageInputStreamSpi.java:55)
	at javax.imageio.ImageIO.createImageInputStream(ImageIO.java:357)
	at javax.imageio.ImageIO.read(ImageIO.java:1304)
	at codecrafter47.bungeetablistplus.managers.SkinManagerImpl.lambda$getSkin$3(SkinManagerImpl.java:136)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
15:30:05 [GRAVE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@2a265ea9, id=56, owner=codecrafter47.bungeetablistplus.BungeePlugin@f31c0c6, task=codecrafter47.bungeetablistplus.managers.SkinManagerImpl$$Lambda$382/930247557@4960fd01, delay=0, period=0, running=true) encountered an exception
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at sun.java2d.Disposer.lambda$static$0(Disposer.java:94)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.java2d.Disposer.<clinit>(Disposer.java:83)
	at javax.imageio.stream.FileImageInputStream.<init>(FileImageInputStream.java:98)
	at javax.imageio.stream.FileImageInputStream.<init>(FileImageInputStream.java:73)
	at com.sun.imageio.spi.FileImageInputStreamSpi.createInputStreamInstance(FileImageInputStreamSpi.java:55)
	at javax.imageio.ImageIO.createImageInputStream(ImageIO.java:357)
	at javax.imageio.ImageIO.read(ImageIO.java:1304)
	at codecrafter47.bungeetablistplus.managers.SkinManagerImpl.lambda$getSkin$3(SkinManagerImpl.java:136)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
15:30:05 [GRAVE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@2a265ea9, id=53, owner=dev.aura.bungeechat.BungeeChat@ed3068a, task=dev.aura.bungeechat.listener.VersionCheckerListener$VersionCheckerTask@2b572ec7, delay=1000, period=0, running=true) encountered an exception
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1105)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
	at sun.net.www.protocol.http.HttpURLConnection.access$100(HttpURLConnection.java:91)
	at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1301)
	at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1299)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1298)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
	at dev.aura.bungeechat.BungeeChat.queryLatestVersion(BungeeChat.java:188)
	at dev.aura.bungeechat.BungeeChat.getLatestVersion(BungeeChat.java:219)
	at dev.aura.bungeechat.listener.VersionCheckerListener$VersionCheckerTask.run(VersionCheckerListener.java:47)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
15:30:06 [GRAVE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@2a265ea9, id=60, owner=codecrafter47.bungeetablistplus.BungeePlugin@f31c0c6, task=codecrafter47.bungeetablistplus.managers.SkinManagerImpl$$Lambda$382/930247557@19ac11cd, delay=0, period=0, running=true) encountered an exception
java.lang.NoClassDefFoundError: Could not initialize class sun.java2d.Disposer
	at javax.imageio.stream.FileImageInputStream.<init>(FileImageInputStream.java:98)
	at javax.imageio.stream.FileImageInputStream.<init>(FileImageInputStream.java:73)
	at com.sun.imageio.spi.FileImageInputStreamSpi.createInputStreamInstance(FileImageInputStreamSpi.java:55)
	at javax.imageio.ImageIO.createImageInputStream(ImageIO.java:357)
	at javax.imageio.ImageIO.read(ImageIO.java:1304)
	at codecrafter47.bungeetablistplus.managers.SkinManagerImpl.lambda$getSkin$3(SkinManagerImpl.java:136)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
15:30:06 [GRAVE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@2a265ea9, id=61, owner=codecrafter47.bungeetablistplus.BungeePlugin@f31c0c6, task=codecrafter47.bungeetablistplus.managers.SkinManagerImpl$$Lambda$382/930247557@2bbf83b0, delay=0, period=0, running=true) encountered an exception
java.lang.NoClassDefFoundError: Could not initialize class sun.java2d.Disposer
	at javax.imageio.stream.FileImageInputStream.<init>(FileImageInputStream.java:98)
	at javax.imageio.stream.FileImageInputStream.<init>(FileImageInputStream.java:73)
	at com.sun.imageio.spi.FileImageInputStreamSpi.createInputStreamInstance(FileImageInputStreamSpi.java:55)
	at javax.imageio.ImageIO.createImageInputStream(ImageIO.java:357)
	at javax.imageio.ImageIO.read(ImageIO.java:1304)
	at codecrafter47.bungeetablistplus.managers.SkinManagerImpl.lambda$getSkin$3(SkinManagerImpl.java:136)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
15:30:06 [GRAVE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@2a265ea9, id=62, owner=codecrafter47.bungeetablistplus.BungeePlugin@f31c0c6, task=codecrafter47.bungeetablistplus.managers.SkinManagerImpl$$Lambda$382/930247557@7dd2c327, delay=0, period=0, running=true) encountered an exception
java.lang.NoClassDefFoundError: Could not initialize class sun.java2d.Disposer
	at javax.imageio.stream.FileImageInputStream.<init>(FileImageInputStream.java:98)
	at javax.imageio.stream.FileImageInputStream.<init>(FileImageInputStream.java:73)
	at com.sun.imageio.spi.FileImageInputStreamSpi.createInputStreamInstance(FileImageInputStreamSpi.java:55)
	at javax.imageio.ImageIO.createImageInputStream(ImageIO.java:357)
	at javax.imageio.ImageIO.read(ImageIO.java:1304)
	at codecrafter47.bungeetablistplus.managers.SkinManagerImpl.lambda$getSkin$3(SkinManagerImpl.java:136)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
15:30:06 [GRAVE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@2a265ea9, id=63, owner=codecrafter47.bungeetablistplus.BungeePlugin@f31c0c6, task=codecrafter47.bungeetablistplus.managers.SkinManagerImpl$$Lambda$382/930247557@3b1ad367, delay=0, period=0, running=true) encountered an exception
java.lang.NoClassDefFoundError: Could not initialize class sun.java2d.Disposer
	at javax.imageio.stream.FileImageInputStream.<init>(FileImageInputStream.java:98)
	at javax.imageio.stream.FileImageInputStream.<init>(FileImageInputStream.java:73)
	at com.sun.imageio.spi.FileImageInputStreamSpi.createInputStreamInstance(FileImageInputStreamSpi.java:55)
	at javax.imageio.ImageIO.createImageInputStream(ImageIO.java:357)
	at javax.imageio.ImageIO.read(ImageIO.java:1304)
	at codecrafter47.bungeetablistplus.managers.SkinManagerImpl.lambda$getSkin$3(SkinManagerImpl.java:136)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jewome62** [comment]
I have already up memory to 2048 Mo and only 17% used
![image](https://user-images.githubusercontent.com/472429/48982266-71f4a880-f0e0-11e8-93e5-af4db9eda623.png)

**Comment by jewome62** [comment]
For détails, the command execute by panel is
`/usr/bin/java" "-Xmx2048M" "-Xms2048M" "-Djline.terminal=jline.UnsupportedTerminal" "-jar" "/srv/multicraft/jar/bungeecord.jar" "nogui" "-Djline.WindowsTerminal.directConsole"`

**Java version**
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by CodeCrafter47** [comment]
I might have spoken too soon.

The root cause of your issue is
```
java.lang.OutOfMemoryError: unable to create new native thread
```
Even though its name suggests that it is not necessarily caused by the lack of memory.
It also happens if there are too many threads already.

Depending on you skills and the level of access you have to the server you might be able to create a thread dump to see if there's an excess amount of threads. Otherwise you can try removing some plugins and see if that solves the issue.
