### ISSUE TITLE
Illegal thread group access

### ISSUE THREAD

**Issue by ronald245** [CodeCrafter47/BungeeTabListPlus#40]
hi codecrafter, 

i had my tablist working perfectly, but recently im having this issue

	Line 17733: 14:26:01 [INFO] Enabled plugin BungeeTabListPlus version 2.1-SNAPSHOT by CodeCrafter47
	Line 19973: 13:42:53 [INFO] Loaded plugin BungeeTabListPlus version 2.1.1-SNAPSHOT by CodeCrafter47
	Line 20000: 13:42:54 [WARNING] [BungeeTabListPlus] Could not load default tabList
	Line 20000: 13:42:54 [WARNING] [BungeeTabListPlus] Could not load default tabList
	Line 20017: 13:42:54 [WARNING] [BungeeTabListPlus] null
	Line 20020: 	at codecrafter47.bungeetablistplus.config.ConfigParser.parse(ConfigParser.java:73)
	Line 20021: 	at codecrafter47.bungeetablistplus.managers.TabListManager.loadTabLists(TabListManager.java:68)
	Line 20021: 	at codecrafter47.bungeetablistplus.managers.TabListManager.loadTabLists(TabListManager.java:68)
	Line 20021: 	at codecrafter47.bungeetablistplus.managers.TabListManager.loadTabLists(TabListManager.java:68)
	Line 20021: 	at codecrafter47.bungeetablistplus.managers.TabListManager.loadTabLists(TabListManager.java:68)
	Line 20022: 	at codecrafter47.bungeetablistplus.BungeeTabListPlus.onEnable(BungeeTabListPlus.java:215)
	Line 20022: 	at codecrafter47.bungeetablistplus.BungeeTabListPlus.onEnable(BungeeTabListPlus.java:215)
	Line 20022: 	at codecrafter47.bungeetablistplus.BungeeTabListPlus.onEnable(BungeeTabListPlus.java:215)
	Line 20023: 	at codecrafter47.bungeetablistplus.BungeePlugin.onEnable(BungeePlugin.java:35)
	Line 20030: 13:42:54 [WARNING] [BungeeTabListPlus] Disabling plugin

**Comment by ronald245** [comment]
weird, after i removed the config and started it up again it started working
