### ISSUE TITLE
NullPointerException - LuckPermsVaultPermission.contextForLookup

### ISSUE THREAD

**Issue by mibby** [CodeCrafter47/BungeeTabListPlus#415]
Paper dev 599 (Spigot 1.13.2)
Waterfall dev 273 (BungeeCord 1.13.2)
BungeeTabList dev 802
LuckPerms dev 889

Console is spamming this error repeatedly.
```
[00:46:43] [Craft Scheduler Thread - 12/ERROR]: [BungeeTabListPlus] Unexpected exception
java.lang.RuntimeException: Exception while querying data from Vault
Vault 1.7.1-b${env.TRAVIS_BUILD_NUMBER}
Permissions LuckPerms 4.4.0
Chat LuckPerms 4.4.0

	at de.codecrafter47.data.bukkit.vault.VaultDataProvider.apply(VaultDataProvider.java:35) ~[?:?]
	at de.codecrafter47.data.api.AbstractDataAccess.lambda$addProvider$0(AbstractDataAccess.java:30) ~[?:?]
	at de.codecrafter47.data.api.AbstractDataAccess.get(AbstractDataAccess.java:44) ~[?:?]
	at de.codecrafter47.data.bukkit.AbstractBukkitDataAccess.get(AbstractBukkitDataAccess.java:43) ~[?:?]
	at de.codecrafter47.data.api.JoinedDataAccess.get(JoinedDataAccess.java:40) ~[?:?]
	at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updatePlayerData(AbstractBridge.java:369) ~[?:?]
	at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.lambda$onMessage$1(AbstractBridge.java:206) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-599]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-599]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-599]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.contextForLookup(LuckPermsVaultPermission.java:400) ~[?:?]
	at me.lucko.luckperms.bukkit.vault.LuckPermsVaultChat.getGroupMeta(LuckPermsVaultChat.java:220) ~[?:?]
	at me.lucko.luckperms.bukkit.vault.AbstractVaultChat.getGroupInfoInteger(AbstractVaultChat.java:360) ~[?:?]
	at de.codecrafter47.data.bukkit.vault.VaultGroupWeightProvider.apply0(VaultGroupWeightProvider.java:34) ~[?:?]
	at de.codecrafter47.data.bukkit.vault.VaultGroupWeightProvider.apply0(VaultGroupWeightProvider.java:25) ~[?:?]
	at de.codecrafter47.data.bukkit.vault.VaultDataProvider.apply(VaultDataProvider.java:33) ~[?:?]
	... 12 more
```

**Comment by mibby** [comment]
Correct me if I'm wrong @lucko but I believe this broke in LuckPerms commit https://github.com/lucko/LuckPerms/commit/62ca2d9c7913aa0a95d766f65b1eb2e88f6a2bfa. So would be an API change.

**Comment by mibby** [comment]
Thanks @lucko. No more exception spam, seems to be fixed with LuckPerms dev 891.
