### ISSUE TITLE
Dynamic-Size error

### ISSUE THREAD

**Issue by salikaaa** [CodeCrafter47/BungeeTabListPlus#425]
Hi, i have big error code.

Caused by: codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.ConstructorException: Can't construct a java object for scalar tag:yaml.org,2002:str; exception=null
 in 'reader', line 13, column 9:
    showTo: 'global'
            ^

        at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.Constructor$ConstructScalar.construct(Constructor.java:420) ~[?:?]
        at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) ~[?:?]
        at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:245) ~[?:?]
        at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:297) ~[?:?]
        ... 18 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_211]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_211]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_211]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_211]
        at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.Constructor$ConstructScalar.construct(Constructor.java:418) ~[?:?]
        at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) ~[?:?]
        at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:245) ~[?:?]
        at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:297) ~[?:?]
        ... 18 more
Caused by: java.lang.IllegalArgumentException: Illegal token 'g' at index 0 in "global"
        at codecrafter47.bungeetablistplus.expression.ExpressionTokenizer.nextToken(ExpressionTokenizer.java:162) ~[?:?]
        at codecrafter47.bungeetablistplus.expression.Expression.<init>(Expression.java:56) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_211]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_211]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_211]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_211]
        at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.Constructor$ConstructScalar.construct(Constructor.java:418) ~[?:?]
        at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) ~[?:?]
        at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:245) ~[?:?]
        at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:297) ~[?:?]
        ... 18 more

My config:
https://www.itextpad.com/INj8Usr45G

Thanks,

**Comment by salikaaa** [comment]
> Hi, i have big error code.
> 
> Caused by: codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.ConstructorException: Can't construct a java object for scalar tag:yaml.org,2002:str; exception=null
> in 'reader', line 13, column 9:
> showTo: 'global'
> ^
> 
> ```
>     at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.Constructor$ConstructScalar.construct(Constructor.java:420) ~[?:?]
>     at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) ~[?:?]
>     at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:245) ~[?:?]
>     at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:297) ~[?:?]
>     ... 18 more
> ```
> 
> Caused by: java.lang.reflect.InvocationTargetException
> at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_211]
> at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_211]
> at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_211]
> at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_211]
> at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.Constructor$ConstructScalar.construct(Constructor.java:418) ~[?:?]
> at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) ~[?:?]
> at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:245) ~[?:?]
> at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:297) ~[?:?]
> ... 18 more
> Caused by: java.lang.IllegalArgumentException: Illegal token 'g' at index 0 in "global"
> at codecrafter47.bungeetablistplus.expression.ExpressionTokenizer.nextToken(ExpressionTokenizer.java:162) ~[?:?]
> at codecrafter47.bungeetablistplus.expression.Expression.(Expression.java:56) ~[?:?]
> at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_211]
> at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_211]
> at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_211]
> at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_211]
> at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.Constructor$ConstructScalar.construct(Constructor.java:418) ~[?:?]
> at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) ~[?:?]
> at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:245) ~[?:?]
> at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:297) ~[?:?]
> ... 18 more
> 
> My config:
> https://www.itextpad.com/INj8Usr45G
> 
> Thanks,
