### ISSUE TITLE
Instance is null

### ISSUE THREAD

**Issue by caneleex** [CodeCrafter47/BungeeTabListPlus#440]
Hey, i'm trying to register a variable but after restarting bungee, my plugin says this:
`15:01:08 [INFO] Enabled plugin BungeeTabListPlus version 2.8.12-SNAPSHOT by CodeCrafter47
15:01:08 [WARNING] Exception encountered when loading plugin: System
java.lang.IllegalStateException: instance is null, is the plugin enabled?
    at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
    at codecrafter47.bungeetablistplus.api.bungee.BungeeTabListPlusAPI.registerVariable(BungeeTabListPlusAPI.java:44)
    at me.canelex.bs.Core.onEnable(Core.java:46)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:247)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:279)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
`
BungeeTabListPlus is enabled as you can see in the log.

**Comment by CodeCrafter47** [comment]
I recommend you check the following things:

 * Do you have `depends: ['BungeeTabListPlus']` in your `bungee.yml`?
 * Does BungeeTabListPlus output any error messages while it's being enabled?

**Comment by caneleex** [comment]
1. Yes, I do
2. Nope

**Comment by caneleex** [comment]
I'm stupid. I just had to change `implementation` to `compileOnly` in build.gradle as I had same problem with LuckPerms.
