### ISSUE TITLE
Error: customPlaceholders is null

### ISSUE THREAD

**Issue by BirkhoffLee** [CodeCrafter47/BungeeTabListPlus#462]
First of all, thanks for creating the fantastic plugin. I had to configure multiple tablists today, and found out the example config `showTo: '${viewer server} == "test1"'` does not work. Am I doing anything wrong here?

```
12:56:46 [WARNING] [BungeeTabListPlus] Failed to load test1.yml
Failed to validate config
in 'reader', line 13, column 1:
showTo: '${viewer server} == "te ...
customPlaceholders is null
at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:250)
at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
at codecrafter47.bungeetablistplus.libs.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
at codecrafter47.bungeetablistplus.libs.snakeyaml.Yaml.loadAs(Yaml.java:410)
at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig.read(YamlConfig.java:102)
at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig.read(YamlConfig.java:98)
at codecrafter47.bungeetablistplus.managers.TabListManager.loadTabLists(TabListManager.java:67)
at codecrafter47.bungeetablistplus.BungeeTabListPlus.onEnable(BungeeTabListPlus.java:343)
at codecrafter47.bungeetablistplus.BungeePlugin.onEnable(BungeePlugin.java:40)
at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:247)
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:279)
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.NullPointerException: customPlaceholders is null
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
at codecrafter47.bungeetablistplus.config.Config.validate(Config.java:71)
at codecrafter47.bungeetablistplus.config.DynamicSizeConfig.validate(DynamicSizeConfig.java:45)
at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:248)
... 13 more
```

**Comment by BirkhoffLee** [comment]
Sorry... I'm dumb.
