### ISSUE TITLE
Premium vanish problem.

### ISSUE THREAD

**Issue by DavidHraSK** [CodeCrafter47/BungeeTabListPlus#465]
.
[22:16:36] [Craft Scheduler Thread - 3/ERROR]: [BungeeTabListPlus] Unexpected exception
java.lang.NoClassDefFoundError: de/myzelyam/api/vanish/VanishAPI
	at de.codecrafter47.data.bukkit.supervanish.SuperVanishIsVanishedProvider.apply(SuperVanishIsVanishedProvider.java:28) ~[?:?]
	at de.codecrafter47.data.bukkit.supervanish.SuperVanishIsVanishedProvider.apply(SuperVanishIsVanishedProvider.java:25) ~[?:?]
	at de.codecrafter47.data.api.AbstractDataAccess.lambda$addProvider$0(AbstractDataAccess.java:30) ~[?:?]
	at de.codecrafter47.data.api.AbstractDataAccess.get(AbstractDataAccess.java:44) ~[?:?]
	at de.codecrafter47.data.bukkit.AbstractBukkitDataAccess.get(AbstractBukkitDataAccess.java:43) ~[?:?]
	at de.codecrafter47.data.api.JoinedDataAccess.get(JoinedDataAccess.java:40) ~[?:?]
	at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updatePlayerData(AbstractBridge.java:369) ~[?:?]
	at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updateData(AbstractBridge.java:304) ~[?:?]
	at codecrafter47.bungeetablistplus.bukkitbridge.BukkitBridge.lambda$onEnable$3(BukkitBridge.java:128) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [server.jar:git-Spigot-d97e08b-880a532]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [server.jar:git-Spigot-d97e08b-880a532]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

Can u help me with this error. If i connect plugin (on paper) to the bungeecord it starts spamming this in the console and server falls. I want to fix this.

**Comment by CodeCrafter47** [comment]
Are you using some kind of PluginManager plugin to load/ unload plugins while the server is running?

**Comment by DavidHraSK** [comment]
Yes im using Plugman

Dňa ne, 24. nov 2019, 17:39 Florian Stober <notifications@github.com>
napísal(a):

**Comment by CodeCrafter47** [comment]
I recommend you try without using Plugman. It can cause problems like that.

**Comment by DavidHraSK** [comment]
Im font using plugman for load.

Dňa ne, 24. nov 2019, 17:49 Florian Stober <notifications@github.com>
napísal(a):

**Comment by DavidHraSK** [comment]
Im restart my server

Dňa ne, 24. nov 2019, 17:50 DavidHraSK <davidgemersky@gmail.com> napísal(a):
