### ISSUE TITLE
Error while try to get Prefix from Luckperms Bungee

### ISSUE THREAD

**Issue by project-play** [CodeCrafter47/BungeeTabListPlus#479]
minecraft version 1.15.1
LuckpermsBungeeversion: 5.0.23
BungeeTabListPlus version: 2.8.11

I become a Error NoClassDeFoundError

[BungeeTabListPlus] Failed to acquire data DataKey(id=luckperms:prefix, scope=Scope(id=bungee:player), type=de.codecrafter47.data.api.TypeToken@62c5bbdc, parameter=null) from Sonicchen99
java.lang.NoClassDefFoundError: me/lucko/luckperms/LuckPerms
at de.codecrafter47.data.bungee.luckperms.LuckPermsPrefixProvider.apply(LuckPermsPrefixProvider.java:33)
at de.codecrafter47.data.bungee.luckperms.LuckPermsPrefixProvider.apply(LuckPermsPrefixProvider.java:29)
at de.codecrafter47.data.api.AbstractDataAccess.lambda$addProvider$0(AbstractDataAccess.java:30)
at de.codecrafter47.data.api.AbstractDataAccess.get(AbstractDataAccess.java:44)
at de.codecrafter47.data.bungee.AbstractBungeeDataAccess.get(AbstractBungeeDataAccess.java:42)
at de.codecrafter47.data.api.JoinedDataAccess.get(JoinedDataAccess.java:40)
at codecrafter47.bungeetablistplus.managers.DataManager.updateData(DataManager.java:71)
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by B4TT3RY** [comment]
#470

**Comment by CodeCrafter47** [comment]
This is fixed in the latest update.
