### ISSUE TITLE
FactionsUUID causes Unexpected Exceptions

### ISSUE THREAD

**Issue by Gaps190118** [CodeCrafter47/BungeeTabListPlus#485]
It appears that FactionsUUID have moved the Role.java file from com.massivecraft.factions.struct to com.massivecraft.factions.perms, causing the following errors:

`[05:27:25] [Craft Scheduler Thread - 28/ERROR]: [BungeeTabListPlus] Unexpected exception
java.lang.NoSuchMethodError: com.massivecraft.factions.FPlayer.getRole()Lcom/massivecraft/factions/struct/Role;
	at de.codecrafter47.data.bukkit.factionsuuid.FactionRankProvider.apply(FactionRankProvider.java:32) ~[?:?]
	at de.codecrafter47.data.bukkit.factionsuuid.FactionRankProvider.apply(FactionRankProvider.java:27) ~[?:?]
	at de.codecrafter47.data.api.AbstractDataAccess.lambda$addProvider$0(AbstractDataAccess.java:30) ~[?:?]
	at de.codecrafter47.data.api.AbstractDataAccess.get(AbstractDataAccess.java:44) ~[?:?]
	at de.codecrafter47.data.bukkit.AbstractBukkitDataAccess.get(AbstractBukkitDataAccess.java:43) ~[?:?]
	at de.codecrafter47.data.api.JoinedDataAccess.get(JoinedDataAccess.java:40) ~[?:?]
	at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updatePlayerData(AbstractBridge.java:369) ~[?:?]
	at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updateData(AbstractBridge.java:304) ~[?:?]
	at codecrafter47.bungeetablistplus.bukkitbridge.BukkitBridge.lambda$onEnable$3(BukkitBridge.java:128) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1618]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[05:27:25] [Craft Scheduler Thread - 28/ERROR]: [BungeeTabListPlus] Unexpected exception
java.lang.NoSuchMethodError: com.massivecraft.factions.Faction.getOnlinePlayers()Ljava/util/ArrayList;
	at de.codecrafter47.data.bukkit.factionsuuid.FactionOnlineMembersProvider.apply(FactionOnlineMembersProvider.java:34) ~[?:?]
	at de.codecrafter47.data.bukkit.factionsuuid.FactionOnlineMembersProvider.apply(FactionOnlineMembersProvider.java:27) ~[?:?]
	at de.codecrafter47.data.api.AbstractDataAccess.lambda$addProvider$0(AbstractDataAccess.java:30) ~[?:?]
	at de.codecrafter47.data.api.AbstractDataAccess.get(AbstractDataAccess.java:44) ~[?:?]
	at de.codecrafter47.data.bukkit.AbstractBukkitDataAccess.get(AbstractBukkitDataAccess.java:43) ~[?:?]
	at de.codecrafter47.data.api.JoinedDataAccess.get(JoinedDataAccess.java:40) ~[?:?]
	at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updatePlayerData(AbstractBridge.java:369) ~[?:?]
	at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updateData(AbstractBridge.java:304) ~[?:?]
	at codecrafter47.bungeetablistplus.bukkitbridge.BukkitBridge.lambda$onEnable$3(BukkitBridge.java:128) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1618]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

**Comment by CodeCrafter47** [comment]
I will look into this soon.

**Comment by CodeCrafter47** [comment]
The latest dev-build should fix the issue.
