### ISSUE TITLE
I must send you that visibly

### ISSUE THREAD

**Issue by Momonche** [CodeCrafter47/BungeeTabListPlus#489]
Hello !
I'm actually trying to update to 3.0.0 (lot of errors)
And I can see this error

```
> 14:40:49 [SEVERE] [BungeeTabListPlus] An internal error occurred! Please send the following StackTrace to the developer in order to help resolving the problem
java.util.concurrent.RejectedExecutionException: event executor terminated
at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:926)
at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:353)
at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:346)
at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:828)
at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:818)
at codecrafter47.bungeetablistplus.managers.BungeePlayerProvider.onPlayerConnected(BungeePlayerProvider.java:61)
at codecrafter47.bungeetablistplus.listener.TabListListener.onPlayerJoin(TabListListener.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:400)
at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:521)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by CodeCrafter47** [comment]
I am afraid that error is not the root cause of the problem, but just an error hiding the error. Can you try the[ latest dev-build](https://ci.codecrafter47.de/job/BungeeTabListPlus/)? I have fixed the error. You will probably see a different error message instead (hopefully also less error messages). Since I think this is caused by a bug in the plugin I am confident we can have this resolved quickly. If possible try to look for the first error that shows up when running the plugin.

**Comment by Momonche** [comment]
I have this error now

```
> 16:35:58 [SEVERE] [BungeeTabListPlus] Failed to activate tab overlay plugins/BungeeTabListPlus/tabLists/lobby.yml
java.lang.NullPointerException
at de.codecrafter47.taboverlay.config.placeholder.DataHolderPlaceholderDataProviderSupplier$PlayerPlaceholderDataProvider.activate(DataHolderPlaceholderDataProviderSupplier.java:62)
at de.codecrafter47.taboverlay.config.placeholder.DataHolderPlaceholderDataProviderSupplier$PlayerPlaceholderDataProvider.activate(DataHolderPlaceholderDataProviderSupplier.java:53)
at de.codecrafter47.taboverlay.config.placeholder.GenericPlaceholder$GenericPlaceholderToStringExpression.onActivation(GenericPlaceholder.java:124)
at de.codecrafter47.taboverlay.config.view.AbstractActiveElement.activate(AbstractActiveElement.java:80)
at de.codecrafter47.taboverlay.config.placeholder.GenericPlaceholder$GenericPlaceholderToStringExpression.activate(GenericPlaceholder.java:104)
at de.codecrafter47.taboverlay.config.expression.AbstractBinaryToBooleanExpression.onActivation(AbstractBinaryToBooleanExpression.java:14)
at de.codecrafter47.taboverlay.config.view.AbstractActiveElement.activate(AbstractActiveElement.java:80)
at de.codecrafter47.taboverlay.config.expression.AbstractBinaryToBooleanExpression.activate(AbstractBinaryToBooleanExpression.java:5)
at de.codecrafter47.taboverlay.config.expression.AbstractToBooleanExpression.onActivation(AbstractToBooleanExpression.java:15)
at de.codecrafter47.taboverlay.config.view.AbstractActiveElement.activate(AbstractActiveElement.java:80)
at de.codecrafter47.taboverlay.config.expression.AbstractToBooleanExpression.activate(AbstractToBooleanExpression.java:7)
at de.codecrafter47.taboverlay.config.player.AbstractPlayerSet$PlayerEntry.<init>(AbstractPlayerSet.java:135)
at de.codecrafter47.taboverlay.config.player.AbstractPlayerSet$PlayerEntry.<init>(AbstractPlayerSet.java:125)
at de.codecrafter47.taboverlay.config.player.AbstractPlayerSet.activate(AbstractPlayerSet.java:40)
at de.codecrafter47.taboverlay.config.player.AbstractPlayerSet.addListener(AbstractPlayerSet.java:67)
at de.codecrafter47.taboverlay.config.player.VisibleToAdminsPlayerSetWrapper.activate(VisibleToAdminsPlayerSetWrapper.java:45)
at de.codecrafter47.taboverlay.config.player.VisibleToAdminsPlayerSetWrapper.addListener(VisibleToAdminsPlayerSetWrapper.java:69)
at de.codecrafter47.taboverlay.config.player.OrderedPlayerSetImpl.activate(OrderedPlayerSetImpl.java:96)
at de.codecrafter47.taboverlay.config.player.OrderedPlayerSetImpl.addListener(OrderedPlayerSetImpl.java:179)
at de.codecrafter47.taboverlay.config.view.components.PlayersComponentView.onActivation(PlayersComponentView.java:62)
at de.codecrafter47.taboverlay.config.view.AbstractActiveElement.activate(AbstractActiveElement.java:80)
at de.codecrafter47.taboverlay.config.view.DynamicSizeContentView.onActivation(DynamicSizeContentView.java:35)
at de.codecrafter47.taboverlay.config.view.AbstractActiveElement.activate(AbstractActiveElement.java:80)
at de.codecrafter47.taboverlay.config.view.TabOverlayView.<init>(TabOverlayView.java:31)
at de.codecrafter47.taboverlay.config.view.TabOverlayView.create(TabOverlayView.java:24)
at de.codecrafter47.taboverlay.config.ConfigTabOverlayProvider.lambda$onActivate$1(ConfigTabOverlayProvider.java:58)
at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
at codecrafter47.bungeetablistplus.util.ExceptionHandlingEventExecutor.run(ExceptionHandlingEventExecutor.java:25)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by Momonche** [comment]
And this one 

```
> 16:44:16 [SEVERE] [BungeeTabListPlus] Failed to activate tab overlay plugins/BungeeTabListPlus/tabLists/default.yml
java.lang.IllegalArgumentException: row + rows <= getRows()
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
at de.codecrafter47.taboverlay.config.area.RectangularArea.createRectangularChild(RectangularArea.java:87)
at de.codecrafter47.taboverlay.config.view.components.ListComponentView.updateLayout(ListComponentView.java:216)
at de.codecrafter47.taboverlay.config.view.components.ListComponentView.onAreaUpdated(ListComponentView.java:62)
at de.codecrafter47.taboverlay.config.view.components.ComponentView.updateArea(ComponentView.java:41)
at de.codecrafter47.taboverlay.config.view.RectangularContentView.onAreaUpdated(RectangularContentView.java:54)
at de.codecrafter47.taboverlay.config.view.components.ComponentView.updateArea(ComponentView.java:41)
at de.codecrafter47.taboverlay.config.view.RectangularContentView.updateTabListSize(RectangularContentView.java:75)
at de.codecrafter47.taboverlay.config.view.RectangularContentView.onActivation(RectangularContentView.java:47)
at de.codecrafter47.taboverlay.config.view.AbstractActiveElement.activate(AbstractActiveElement.java:80)
at de.codecrafter47.taboverlay.config.view.TabOverlayView.<init>(TabOverlayView.java:31)
at de.codecrafter47.taboverlay.config.view.TabOverlayView.create(TabOverlayView.java:24)
at de.codecrafter47.taboverlay.config.ConfigTabOverlayProvider.lambda$onActivate$1(ConfigTabOverlayProvider.java:58)
at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
at codecrafter47.bungeetablistplus.util.ExceptionHandlingEventExecutor.run(ExceptionHandlingEventExecutor.java:25)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by CodeCrafter47** [comment]
Can you give me the config files that trigger these errors?

**Comment by Momonche** [comment]
Default config.yml from 3.0.1
Default default.yml from 3.0.1

My lobby.yml : 
https://pastebin.com/LQsVum22

**Comment by Momonche** [comment]
Ok I just find the issue in my lobby.yml

```
  lobby:
    filter: |-
      ${player server} == ${viewer server}
```

I replace that by

```
  lobby:
    filter: |-
      ${player server} == "lobby"
```

But the default.yml continue to give me errors

**Comment by CodeCrafter47** [comment]
Can you check if the latest update fixes your issues?

**Comment by Momonche** [comment]
Seems to work, no errors

Thanks !
