### ISSUE TITLE
Issue with showto??

### ISSUE THREAD

**Issue by tiarnia** [CodeCrafter47/BungeeTabListPlus#491]
i have tryed everything i can find in the guid but idk what that means im doing wrong 

[23:57:57 WARN] [BungeeTabListPlus]: Failed to load default.yml
codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.ConstructorException: Cannot create property=playerSets for JavaBean=codecrafter47.bungeetablistplus.config.FixedSizeConfig@43b4fe19
 in 'reader', line 13, column 1:
    showTo: all
    ^
No single argument constructor found for class codecrafter47.bungeetablistplus.config.PlayerSet
 in 'reader', line 19, column 3:
      all_players: all
      ^

        at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:312) ~[?:?]
        at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189) ~[?:?]
        at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) ~[?:?]
        at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:245) ~[?:?]
        at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141) ~[?:?]
        at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127) ~[?:?]
        at codecrafter47.bungeetablistplus.libs.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[?:?]
        at codecrafter47.bungeetablistplus.libs.snakeyaml.Yaml.loadAs(Yaml.java:410) ~[?:?]
        at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig.read(YamlConfig.java:102) ~[?:?]
        at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig.read(YamlConfig.java:98) ~[?:?]
        at codecrafter47.bungeetablistplus.managers.TabListManager.loadTabLists(TabListManager.java:67) ~[?:?]
        at codecrafter47.bungeetablistplus.BungeeTabListPlus.onEnable(BungeeTabListPlus.java:343) ~[?:?]
        at codecrafter47.bungeetablistplus.BungeePlugin.onEnable(BungeePlugin.java:40) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:285) ~[waterfall-312.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281) ~[waterfall-312.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[waterfall-312.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-312.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
Caused by: codecrafter47.bungeetablistplus.libs.snakeyaml.error.YAMLException: No single argument constructor found for class codecrafter47.bungeetablistplus.config.PlayerSet
        at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.Constructor$ConstructScalar.construct(Constructor.java:396) ~[?:?]
        at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) ~[?:?]
        at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:245) ~[?:?]
        at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:373) ~[?:?]
        at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:147) ~[?:?]
        at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:354) ~[?:?]
        at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:170) ~[?:?]
        at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) ~[?:?]
        at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:245) ~[?:?]
        at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:297) ~[?:?]

**Comment by CodeCrafter47** [comment]
You are using an old version of the plugin. Please download the latest version.
