### ISSUE TITLE
Prefixes show up on one server, but not the others 

### ISSUE THREAD

**Issue by FuturePinger** [CodeCrafter47/BungeeTabListPlus#506]
I do get this error. I feel like Im missing a placeholder but im not sure which one!

01:56:39 [WARNING] [BungeeTabListPlus] An unexpected error occurred: null
java.lang.NullPointerException
at codecrafter47.bungeetablistplus.placeholder.PlayerPlaceholderResolver.lambda$new$0(PlayerPlaceholderResolver.java:78)
at de.codecrafter47.taboverlay.config.placeholder.AbstractPlayerPlaceholderResolver.lambda$null$5(AbstractPlayerPlaceholderResolver.java:26)
at de.codecrafter47.taboverlay.config.placeholder.DataHolderPlaceholderDataProviderSupplier.get(DataHolderPlaceholderDataProviderSupplier.java:45)
at de.codecrafter47.taboverlay.config.placeholder.DataHolderPlaceholderDataProviderSupplier.access$200(DataHolderPlaceholderDataProviderSupplier.java:21)
at de.codecrafter47.taboverlay.config.placeholder.DataHolderPlaceholderDataProviderSupplier$PlayerPlaceholderDataProvider.getData(DataHolderPlaceholderDataProviderSupplier.java:102)
at de.codecrafter47.taboverlay.config.placeholder.GenericPlaceholder$GenericPlaceholderTextView.getText(GenericPlaceholder.java:74)
at de.codecrafter47.taboverlay.config.view.text.TextViewList.getText(TextViewList.java:24)
at de.codecrafter47.taboverlay.config.view.HeaderAndFooterView.updateHeaderAndFooter(HeaderAndFooterView.java:56)
at de.codecrafter47.taboverlay.config.view.HeaderAndFooterView.onTextUpdated(HeaderAndFooterView.java:71)
at de.codecrafter47.taboverlay.config.placeholder.GenericPlaceholder$GenericPlaceholderTextView.run(GenericPlaceholder.java:99)
at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4698)
at java.base/java.util.Collections$SetFromMap.forEach(Collections.java:5581)
at de.codecrafter47.data.api.DataCache.updateValue(DataCache.java:39)
at codecrafter47.bungeetablistplus.managers.DataManager.lambda$updateIfNecessary$0(DataManager.java:137)
at codecrafter47.bungeetablistplus.util.ExceptionHandlingEventExecutor.run(ExceptionHandlingEventExecutor.java:25)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by CodeCrafter47** [comment]
That is a bug in the plugin. Fixed it in c6358eee2e74de2f32a9d09a0773efbd51f45abb.
