### ISSUE TITLE
Spectator mode handling issue: viewer neither in freePlayers set and nor in tab list

### ISSUE THREAD

**Issue by JasonHorkles** [CodeCrafter47/BungeeTabListPlus#511]
```
[17:26:18 ERROR] [BungeeTabListPlus.JasonHorkles]: [JasonHorkles] Spectator mode handling issue: highestUsedSlotIndex not marked as dirty
[17:26:18 WARN] [io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler$$Lambda$660/1752355673@3d778ae2
java.lang.NullPointerException: null
        at codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler$CustomContentTabOverlayHandler.update(AbstractTabOverlayHandler.java:1609) ~[?:?]
        at codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler.update(AbstractTabOverlayHandler.java:476) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b2797bc:315]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```
I got this when switching servers (was in spectator mode in both if that makes a difference, however it said the error for each player)
Running version 3.0.9-SNAPSHOT

I also got this warning later on
```
[21:21:51 WARN] [io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler$$Lambda$660/1752355673@49aae8f6
java.lang.NullPointerException: null
```

**Comment by CodeCrafter47** [comment]
The new version 3.0.9 fixes this issue.
