### ISSUE TITLE
[Bug] Bridge functionality not available

### ISSUE THREAD

**Issue by Baktus79** [CodeCrafter47/BungeeTabListPlus#519]
BungeeTabListPlus broke on the new update of LuckPerms on BungeeCord.

```
[WARNING] Exception encountered when loading plugin: BungeeTabListPlus
java.lang.LinkageError: loader (instance of  net/md_5/bungee/api/plugin/PluginClassloader): attempted duplicate class definition for name: "net/luckperms/api/LuckPerms"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at net.md_5.bungee.api.plugin.PluginClassloader.findClass0(PluginClassloader.java:44)
	at net.md_5.bungee.api.plugin.PluginClassloader.findClass0(PluginClassloader.java:56)
	at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:37)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at de.codecrafter47.data.bungee.PlayerDataAccess.isClassPresent(PlayerDataAccess.java:175)
	at de.codecrafter47.data.bungee.PlayerDataAccess.<init>(PlayerDataAccess.java:107)
	at codecrafter47.bungeetablistplus.managers.DataManager.<init>(DataManager.java:85)
	at codecrafter47.bungeetablistplus.BungeeTabListPlus.onEnable(BungeeTabListPlus.java:255)
	at codecrafter47.bungeetablistplus.BungeePlugin.onEnable(BungeePlugin.java:40)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:280)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

The console on BungeeCord spams the message 
`[SEVERE] [BungeeTabListPlus] Internal error - Bridge functionality not available for xxx`

Seems to be fine on the Paper side. 

**BungeeTabListPlus version**: 3.0.9
**Paper version**: 112 (MC: 1.15.2)
**BungeeCord version**: 1483
**Luckperms version**: 5.0.78

**Comment by BradleyGRR** [comment]
Works perfectly fine for me, what's your config like?

**Comment by Baktus79** [comment]
This one has always worked for me. The config remain the same as always, but it broke when I updated the server.

```yaml
# This is the configuration file of BungeeTabListPlus
# See https://github.com/CodeCrafter47/BungeeTabListPlus/wiki for additional information

# if enabled the plugin checks for new versions automatically.
# Use /BTLP to see whether a new version is available
# this does NOT automatically install an update
checkForUpdates: true

# this notifies admins (everyone with the permission `bungeetablistplus.admin`) if an update is available
notifyAdminsIfUpdateAvailable: true

# Interval (in seconds) at which all servers of your network get pinged to check whether they are online
# If you intend to use the {onlineState:SERVER} variable set this to 2 or any value you like
# setting this to -1 disables this feature
pingDelay: -1

# those fakeplayers will randomly appear on the tablist. If you don't put any names there then no fakeplayers will appear
fakePlayers: []

# Servers which you wish to show their own tabList (The one provided by bukkit)
# Players on these servers don't see the custom tab list provided by BungeeTabListPlus
excludeServers: []

# Players on these servers are hidden from the tab list.
# Doesn't necessarily hide the server from the tab list.
hiddenServers: []

# players which are permanently hidden from the tab list
# you can either put your username or your uuid (with dashes) here
# don't use this. you have absolutely no reason to hide from anyone. on your own server.
hiddenPlayers: []

# Time zone to use for the {time} variable
# Can be full name like "America/Los_Angeles"
# or custom id like "GMT+8"
time-zone: Europe/Berlin

# Custom placeholders
customPlaceholders: {}
```

```yaml
showTo: "all"
priority: 0

playerSets:
  all_players: # A player set containing all players
    filter: "true"

# A simple header and footer
showHeaderFooter: true
header:
- |-
  &aVelkommen til
  &aVestlandet MC, &f${viewer name}
headerAnimationUpdateInterval: 2.0
footer:
- |-
  &6---===O===---
  &2Server TPS: &6${viewer server tps}
  &2Antall pålogget: &6${playerset:all_players size}
  &2Din rank: ${viewer vault_prefix}
  &6---===O===---

footerAnimationUpdateInterval: 1.0

# We want a dynamic size tab list
type: DYNAMIC_SIZE

customPlaceholders:
  staff:
    !switch
    parameters: 1
    expression: ${player vault_prefix}
    replacements:
      "&6&lAdmin &e": "&6"
      "&6&lMod &e": "&6"
      "&9&lUtvikler &e": "&6"
      "&6&lEier &e": "&6"
      "&6&lHjelper &e": "&6"
      "&6&lLærling &e": "&6"
    defaultReplacement: "&7"
  donation:
    !switch
    parameters: 1
    expression: ${player vault_prefix}
    replacements:
      "&2&lSmaragd &7": " &2&o[S]"
      "&4&lRubin &7": " &4&o[R]"
      "&a&lJuvel &7": " &a&o[J]"

# Below are the options specific to the dynamic size tab list

# Here you can configure which players to display by specifying a player set.
# For this example we are using the `all_players` player set created above.
playerSet: all_players

# Here the order of the players can be configured.
playerOrder: "alphabetically"

# This option controls the format of the players names.
playerComponent: "${staff}${player name}${donation} ${player cmi_user_afk_symbol}"
```

**Comment by CodeCrafter47** [comment]
This should not be happening. Try updating BungeeCord and your other BungeeCord plugins.

**Comment by Baktus79** [comment]
I have done so but nothing new. Still broken

**Comment by Baktus79** [comment]
These are my plugins on BungeeCord
![image](https://user-images.githubusercontent.com/19745447/75294458-c6795d00-5828-11ea-9cd7-03a2edb3c69a.png)

I updated LuckPerms today and still nothing

**Comment by Baktus79** [comment]
I removed the whole BungeeCord folder and restructured it. Seems to be working fine now....
