### ISSUE TITLE
Unsupported size 80

### ISSUE THREAD

**Issue by norfair00** [CodeCrafter47/BungeeTabListPlus#531]
I have error on set size to 80:

Log
```
15.03 01:00:47 [Server] INFO CONSOLE executed command: /btlp reload
15.03 01:00:47 [Server] INFO Successfully reloaded BungeeTabListPlus.
15.03 01:00:47 [Server] ERROR [BungeeTabListPlus]: Failed to activate tab overlay plugins\BungeeTabListPlus\tabLists\default.yml
15.03 01:00:47 [Server] INFO java.lang.IllegalArgumentException: Unsupported size 80
15.03 01:00:47 [Server] INFO at de.codecrafter47.taboverlay.config.view.RectangularContentView.<init>(RectangularContentView.java:30) ~[?:?]
15.03 01:00:47 [Server] INFO at de.codecrafter47.taboverlay.config.template.RectangularTabOverlayTemplate.createContentView(RectangularTabOverlayTemplate.java:22) ~[?:?]
15.03 01:00:47 [Server] INFO at de.codecrafter47.taboverlay.config.view.TabOverlayView.create(TabOverlayView.java:22) ~[?:?]
15.03 01:00:47 [Server] INFO at de.codecrafter47.taboverlay.config.ConfigTabOverlayProvider.lambda$onActivate$1(ConfigTabOverlayProvider.java:58) ~[?:?]
15.03 01:00:47 [Server] INFO at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[travertine-134.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:eee1a2e:134]
15.03 01:00:47 [Server] INFO at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106) ~[travertine-134.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:eee1a2e:134]
15.03 01:00:47 [Server] INFO at codecrafter47.bungeetablistplus.util.ExceptionHandlingEventExecutor.run(ExceptionHandlingEventExecutor.java:25) ~[?:?]
15.03 01:00:47 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[travertine-134.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:eee1a2e:134]
15.03 01:00:47 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[travertine-134.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:eee1a2e:134]
15.03 01:00:47 [Server] INFO at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[travertine-134.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:eee1a2e:134]
15.03 01:00:47 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212-1-ojdkbuild]
15.03 01:00:47 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212-1-ojdkbuild]
15.03 01:00:47 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212-1-ojdkbuild]
```

Config from wiki https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Configuration-Basics-Part-6---Fixed-Size-Tablist-Introduction
```yaml
showTo: all
priority: 1

showHeaderFooter: false

playerSets: {} # none yet

type: FIXED_SIZE

size: 80

defaultIcon: colors/black.png
defaultPing: 1000

components:
- 'Slot 1'
- 'Slot 2'
- 'Slot 3'
- 'Slot 4'
- 'Slot 5'
- 'Slot 6'
- 'Slot 7'
- 'Slot 8'
- 'Slot 9'
- 'Slot 10'
```

**Comment by norfair00** [comment]
On 1.7.10 server

**Comment by CodeCrafter47** [comment]
For 1.7.10 the `size` specified in BungeeTabListPlus's config must be the same as the `tabSize` in BungeeCord's config.
