### ISSUE TITLE
IllegalStateException: Player is either on another team or not on any team. Cannot remove from team ' BTLPb144554b 80'.

### ISSUE THREAD

**Issue by mibby** [CodeCrafter47/BungeeTabListPlus#546]
Waterfall dev 326 (BungeeCord Fork)
Purpur dev 508 (Paper Fork for Spigot 1.15.2)
BungeeTabListPlus dev 937

```
[03:45:31] [main/FATAL]: Error executing task on Client
java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team ' BTLPb144554b 80'.
	at cwl.b(SourceFile:236) ~[cwl.class:?]
	at dnp.a(SourceFile:2112) ~[dnp.class:?]
	at os.a(SourceFile:122) ~[os.class:?]
	at os.a(SourceFile:16) ~[os.class:?]
	at lv.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:33) ~[lv.class:?]
	at lv$$Lambda$2387/1274735625.run(Unknown Source) ~[?:?]
	at ais.c(ThreadTaskExecutor.java:173) [ais.class:?]
	at aiw.c(SourceFile:23) [aiw.class:?]
	at ais.w(ThreadTaskExecutor.java:135) [ais.class:?]
	at ais.bk(ThreadTaskExecutor.java:115) [ais.class:?]
	at dbn.d(SourceFile:956) [dbn.class:?]
	at dbn.d(SourceFile:619) [dbn.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:204) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.1.jar:2.1]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.1.jar:2.1]
```

```
[03:45:31] [main/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
	at dnp.a(SourceFile:565) ~[dnp.class:?]
	at mc.a(SourceFile:57) ~[mc.class:?]
	at mc.a(SourceFile:11) ~[mc.class:?]
	at lv.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:33) ~[lv.class:?]
	at lv$$Lambda$2387/1274735625.run(Unknown Source) ~[?:?]
	at ais.c(ThreadTaskExecutor.java:173) [ais.class:?]
	at aiw.c(SourceFile:23) [aiw.class:?]
	at ais.w(ThreadTaskExecutor.java:135) [ais.class:?]
	at ais.bk(ThreadTaskExecutor.java:115) [ais.class:?]
	at dbn.d(SourceFile:956) [dbn.class:?]
	at dbn.d(SourceFile:619) [dbn.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:204) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.1.jar:2.1]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.1.jar:2.1]
```

**Comment by CodeCrafter47** [comment]
The error mentioning BTLP is definitely caused by BTLP. I can't tell about the others. In general a lot of plugins are sending faulty scoreboard packets, but I don't think it affects gameplay, so there's nothing to worry about.

**Comment by mibby** [comment]
Did some digging and testing to diagnose some issues. Two of the exceptions are caused by some patch incompatibilities with Citizens and something else in Tuinity and Purpur (the latter inheriting tuinity patches). 

The only issue would be ``Player is either on another team or not on any team. Cannot remove from team ' BTLPb144554b 80'`` which I'm not sure how it could occur if BTLP isn't suppose to and doesn't touch player scoreboards / grouping at all. Maybe it errored _because_ players weren't assigned to any scoreboard group yet with NametagEdit? But I'm not sure why BTLP would care in the first place since it doesn't touch scoreboard groups and gets everything from the vault prefix.

**Comment by CodeCrafter47** [comment]
BTLP heavily modifies the scoreboard. It uses teams to order the players and custom slots in the tab list.
When using all 80 slots of the tab list players without a team are put in the ` BTLPxxx 80` team (otherwise they'd show up in the first slot and ruin the layout).
When using less than 80 slots each player is assigned to a team ` BTLPxxx yy` where `yy` is the number of the slot the player is displayed in. If the player is in a different team already BTLP will copy all the properties of that team to the ` BTLPxxx yy` team. That way prefixes and stuff work as you would expect and you are unlikely to notice that BTLP modified your teams.

**Comment by mibby** [comment]
So there's no way to prevent this client error? :( It occurs with BTLP dev 949 and NametagEdit plugin.

```
[09:23:18] [main/FATAL]: Error executing task on Client
java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team ' BTLPe2ad8cd6 80'.
	at cwl.b(SourceFile:236) ~[cwl.class:?]
	at dnp.a(SourceFile:2112) ~[dnp.class:?]
	at os.a(SourceFile:122) ~[os.class:?]
	at os.a(SourceFile:16) ~[os.class:?]
	at lv.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:33) ~[lv.class:?]
	at lv$$Lambda$2383/852584726.run(Unknown Source) ~[?:?]
	at ais.c(ThreadTaskExecutor.java:173) [ais.class:?]
	at aiw.c(SourceFile:23) [aiw.class:?]
	at ais.w(ThreadTaskExecutor.java:135) [ais.class:?]
	at ais.bk(ThreadTaskExecutor.java:115) [ais.class:?]
	at dbn.d(SourceFile:956) [dbn.class:?]
	at dbn.d(SourceFile:619) [dbn.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:204) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.1.jar:2.1]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.1.jar:2.1]
```

**Comment by mibby** [comment]
Switching back to the plugin TAB instead of NameTagEdit seems to prevent BTLP from causing errors. Maybe it's because TAB is setting a team before BTLP checks while NameTagEdit doesn't before BTLP? 

It's easily reproducible with NTE and not visible (as far as I've tested so far) with TAB.

**Comment by CodeCrafter47** [comment]
Can you check if the latest dev-build fixes the issue?

**Comment by mibby** [comment]
Looking at my client logs, unfortunately I still get the issue. This is with using TAB.

BTLP dev 985
TAB Premium v2.7.4-pre11

```
[18:19:17] [main/FATAL]: Error executing task on Client
java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team ' BTLPf59f5c1c 00'.
	at net.minecraft.class_269.method_1157(class_269.java:236) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_634.method_11099(class_634.java:2112) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_2755.method_11860(class_2755.java:122) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_2755.method_11054(class_2755.java:16) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:33) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:173) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:135) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:956) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:619) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:204) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.8.2+build.194.jar:?]
[18:19:17] [main/FATAL]: Error executing task on Client
java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team ' BTLPf59f5c1c 02'.
	at net.minecraft.class_269.method_1157(class_269.java:236) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_634.method_11099(class_634.java:2112) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_2755.method_11860(class_2755.java:122) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_2755.method_11054(class_2755.java:16) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:33) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:173) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:135) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:956) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:619) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:204) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.8.2+build.194.jar:?]
[18:19:17] [main/FATAL]: Error executing task on Client
java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team ' BTLPf59f5c1c 04'.
	at net.minecraft.class_269.method_1157(class_269.java:236) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_634.method_11099(class_634.java:2112) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_2755.method_11860(class_2755.java:122) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_2755.method_11054(class_2755.java:16) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:33) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:173) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:135) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:956) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:619) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:204) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.8.2+build.194.jar:?]
[18:19:17] [main/FATAL]: Error executing task on Client
java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team ' BTLPf59f5c1c 05'.
	at net.minecraft.class_269.method_1157(class_269.java:236) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_634.method_11099(class_634.java:2112) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_2755.method_11860(class_2755.java:122) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_2755.method_11054(class_2755.java:16) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:33) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:173) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:135) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:956) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:619) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:204) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.8.2+build.194.jar:?]
[18:19:17] [main/FATAL]: Error executing task on Client
java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team ' BTLPf59f5c1c 06'.
	at net.minecraft.class_269.method_1157(class_269.java:236) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_634.method_11099(class_634.java:2112) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_2755.method_11860(class_2755.java:122) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_2755.method_11054(class_2755.java:16) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:33) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:173) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:135) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:956) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:619) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:204) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.8.2+build.194.jar:?]
[18:19:17] [main/FATAL]: Error executing task on Client
java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team ' BTLPf59f5c1c 07'.
	at net.minecraft.class_269.method_1157(class_269.java:236) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_634.method_11099(class_634.java:2112) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_2755.method_11860(class_2755.java:122) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_2755.method_11054(class_2755.java:16) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:33) ~[intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:173) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:135) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:956) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:619) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:204) [intermediary-fabric-loader-0.8.2+build.194-1.15.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.8.2+build.194.jar:?]
```

**Comment by mibby** [comment]
I went back to a dynamic scoreboard with BTLP for testing (no fake player slots) and noticed the client errors still occur whenever someone joins or quits.

https://paste.ubuntu.com/p/RqsdPjWQKH/

**Comment by CodeCrafter47** [comment]
Are you using TAB on spigot or Bungee?

**Comment by mibby** [comment]
I'm using TAB on Spigot. I only use it for colorizing the nametags above players heads.
