### ISSUE TITLE
NullPointerException on setCustomTabList

### ISSUE THREAD

**Issue by matthijs2704** [CodeCrafter47/BungeeTabListPlus#558]
I'm getting the following weird error when I use the BungeeTabListPlus API in my bungee plugin. I am not able to set the custom tab list on my proxyplayer. (Even when just compiling the example bungee plugin and using that). It raises the following exception:
```
java.lang.NullPointerException: null
	at codecrafter47.bungeetablistplus.managers.API.setCustomTabList0(API.java:54) ~[?:?]
	at codecrafter47.bungeetablistplus.api.bungee.BungeeTabListPlusAPI.setCustomTabList(BungeeTabListPlusAPI.java:87) ~[?:?]
	at nl.matthijs2704.bungee.btlpgeyser.BTLPGeyser$1.execute(BTLPGeyser.java:42) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:192) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:142) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
	at mc-sudo.hazae41.minecraft.kutils.bungee.CommandsKt.execute(Commands.kt:3) ~[?:?]
	at hazae41.minecraft.sudo.bungee.EventsKt$makeListeners$$inlined$listen$1.onEvent(Events.kt:52) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:46) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:434) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:149) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
	at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:60) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
```

I'm running on the latest Waterfall 1.15.2 and BungeeTabListPlus version 3.1.0. Any idea what is going wrong? Any ideas would be appreciated!

**Comment by CodeCrafter47** [comment]
It's a bug. But I fixed it a few days ago. So you an just grab the[ latest dev-build](https://ci.codecrafter47.de/job/BungeeTabListPlus/) and then everything should work as expected.

**Comment by matthijs2704** [comment]
Thanks! Indeed that fixed it.
