### ISSUE TITLE
Problem in launch

### ISSUE THREAD

**Issue by Raphy123** [CodeCrafter47/BungeeTabListPlus#56]
Hello 

I have this error when I launch BungeeCord latest ver.

17:54:39 [AVERTISSEMENT] Error enabling plugin BungeeTabListPlus
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:34)
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:297)
at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:205)
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:247)
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
... 18 more

**Comment by CodeCrafter47** [comment]
How did you obtain the plugin file?

**Comment by Raphy123** [comment]
On the website of Spigot. With 2.1.5, that was Ok, when I put 2.2.5, not working. And when I try to return on 2.1.5 ver; always not working..

**Comment by CodeCrafter47** [comment]
The zip file on spigot website contains two jar files. You should only install the one labeled BungeeTabListPlus-2.2.5.jar on your BungeeCord server. You can also look in the wiki how to install the plugin: https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Installation

**Comment by Raphy123** [comment]
I test that

**Comment by Raphy123** [comment]
Still the same problem .. I do not understand.

**Comment by DistortedDorian** [comment]
@Raphy123 Simply download the latest plugin version off Spigot and reset all the config files and readd all customizations you had from scratch.

**Comment by CodeCrafter47** [comment]
The problem is you put the bukkit plugin on bungee. Which fails for obvious reasons.
