### ISSUE TITLE
[pool-3-thread-54/ERROR] [bungeetablistplus]: Unexpected exception 

### ISSUE THREAD

**Issue by neverfind** [CodeCrafter47/BungeeTabListPlus#567]
My server console is being completely overun by this error, it's spitting it every second a player is on the server. Everything on the server, is working as normal, the console is just being flooded with that error. 

BungeeTabListPlus Version: 3.2.0
Forge: 1.12.2 14.23.5.2847
SpongeForge: 2838-7.2.0
WaterFall: 1.15 340

` [19:17:32] [pool-3-thread-54/ERROR] [bungeetablistplus]: Unexpected exception
java.lang.ClassCastException: org.spongepowered.common.service.permission.SpongeSubjectReference cannot be cast to org.spongepowered.api.service.permission.Subject
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_242]
at java.util.Collections$2.tryAdvance(Collections.java:4719) ~[?:1.8.0_242]
at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242]
at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_242]
at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531) ~[?:1.8.0_242]
at de.codecrafter47.data.sponge.sponge5.Sponge5.getPrimaryGroup(Sponge5.java:26) ~[Sponge5.class:?]
at de.codecrafter47.data.api.AbstractDataAccess.lambda$addProvider$0(AbstractDataAccess.java:30) ~[AbstractDataAccess.class:?]
at de.codecrafter47.data.api.AbstractDataAccess.get(AbstractDataAccess.java:44) ~[AbstractDataAccess.class:?]
at de.codecrafter47.data.sponge.AbstractSpongeDataAccess.get(AbstractSpongeDataAccess.java:35) ~[AbstractSpongeDataAccess.class:?]
at de.codecrafter47.data.api.JoinedDataAccess.get(JoinedDataAccess.java:40) ~[JoinedDataAccess.class:?]
at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updatePlayerData(AbstractBridge.java:369) ~[AbstractBridge.class:?]
at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updateData(AbstractBridge.java:304) ~[AbstractBridge.class:?]
at codecrafter47.bungeetablistplus.spongebridge.SpongePlugin.lambda$onServerStart$3(SpongePlugin.java:146) ~[SpongePlugin.class:?]
at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.2.0]
at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197) ~[SchedulerBase.class:1.12.2-2838-7.2.0]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] `

**Comment by neverfind** [comment]
Using the latest snapshot of spongebridge, the issue is non existent.
