### ISSUE TITLE
Bungee error on switching servers.

### ISSUE THREAD

**Issue by Zilacon** [CodeCrafter47/BungeeTabListPlus#587]
Errors when players switch servers, im guessing these players disconnected while being sent to the HUB when the server they were on restarted.

```
22:20:40 [WARNING] Error dispatching event ServerSwitchEvent(player=teddiiee) to listener codecrafter47.bungeetablistplus.managers.TabViewManager@13ef6f49
java.lang.AssertionError: Received ServerSwitchEvent for non-existent player teddiiee
at codecrafter47.bungeetablistplus.managers.TabViewManager.onServerConnected(TabViewManager.java:98)
at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:17)
at net.md_5.bungee.event.EventBus.post(EventBus.java:32)
at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:312)
at net.md_5.bungee.LegacyServerConnector.handle(LegacyServerConnector.java:172)
at net.md_5.bungee.protocol.packet.Login.handle(Login.java:107)
at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:78)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
at net.md_5.bungee.protocol.PacketDecoder.firePacket(PacketDecoder.java:31)
at net.md_5.bungee.protocol.LegacyPacketDecoder.decode(LegacyPacketDecoder.java:105)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at java.lang.Thread.run(Thread.java:748)
22:20:42 [SEVERE] [BungeeTabListPlus] Internal error - Bridge functionality not available for teddiiee
22:20:52 [WARNING] Error dispatching event ServerSwitchEvent(player=kippre7790) to listener codecrafter47.bungeetablistplus.managers.TabViewManager@13ef6f49
java.lang.AssertionError: Received ServerSwitchEvent for non-existent player kippre7790
at codecrafter47.bungeetablistplus.managers.TabViewManager.onServerConnected(TabViewManager.java:98)
at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:17)
at net.md_5.bungee.event.EventBus.post(EventBus.java:32)
at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:312)
at net.md_5.bungee.LegacyServerConnector.handle(LegacyServerConnector.java:172)
at net.md_5.bungee.protocol.packet.Login.handle(Login.java:107)
at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:78)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
at net.md_5.bungee.protocol.PacketDecoder.firePacket(PacketDecoder.java:31)
at net.md_5.bungee.protocol.LegacyPacketDecoder.decode(LegacyPacketDecoder.java:105)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at java.lang.Thread.run(Thread.java:748)
22:20:54 [SEVERE] [BungeeTabListPlus] Internal error - Bridge functionality not available for kippre7790
```

**Comment by CodeCrafter47** [comment]
I don't think BungeeTabListPlus is causing the issue. It is just telling you that there is something wrong. In perticular it receives a ServerSwitchEvent for a player who has already been disconnected, i.e. the plugin received a disconnect event before.
