### ISSUE TITLE
Plugin version for legacy servers.

### ISSUE THREAD

**Issue by Zilacon** [CodeCrafter47/BungeeTabListPlus#594]
I have the TPS shown on my tablist but i need the bukkit plugin for 1.5.2 and 1.6.4.
But even if i get it from that far back, do those older versions support the TPS feature?
If not could some compatibility be added into a newer version for 1.5/1.6?

**Comment by CodeCrafter47** [comment]
I've made a couple of small changes to allow the bridge plugin to work on an 1.5.2 server. When using the[ latest dev-build](https://ci.codecrafter47.de/job/BungeeTabListPlus/) it now loads without errors. Haven't tested with players.

**Comment by Zilacon** [comment]
@CodeCrafter47 doesnt work.
```
15:23:43 [SEVERE] Could not load 'plugins/BungeeTabListPlus_BukkitBridge-3.4.1-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ClassNotFoundException: Failed to remap class codecrafter47.bungeetablistplus.BukkitPlugin
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:164)
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:307)
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:231)
	at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:256)
	at cpw.mods.fml.common.event.FMLServerAboutToStartEvent.<init>(FMLServerAboutToStartEvent.java:30)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:527)
	at cpw.mods.fml.common.LoaderState.getEvent(LoaderState.java:84)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:103)
	at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:807)
	at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:309)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:212)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:172)
	at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
Caused by: java.lang.ClassNotFoundException: Failed to remap class codecrafter47.bungeetablistplus.BukkitPlugin
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:448)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:362)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153)
	... 15 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:424)
	at net.md_5.specialsource.RemapperPreprocessor.preprocess(RemapperPreprocessor.java:83)
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:404)
	... 22 more
```

**Comment by CodeCrafter47** [comment]
Looks like you're using the thing that combines Bukkit & Forge (forgot what it's called). I think the bug is with that. There is no issue with spigot 1.5.2.

**Comment by Zilacon** [comment]
@CodeCrafter47 
Yeah im using MCPC+ you can download it here: https://archive.mcmirror.io/MCPC%2B/

**Comment by CodeCrafter47** [comment]
I've come up with a work-around. You can make it function by disabling mcpc+'s custom class loader for the bridge plugin. To do so, you need to edit `mcpc.yml`. In the `plugin-settings` category, leave `default` as is and add a new entry `BungeeTabListPlus` below, where you set `custom-class-loader` to `false`.
```yaml
plugin-settings:
  default:
    # ...    <- leave as is
  # add the following two lines
  BungeeTabListPlus:
    custom-class-loader: false
```

**Comment by Zilacon** [comment]
@CodeCrafter47 Didnt even know you could do that. Now its giving this error:
```
01:56:13 [SEVERE] Could not load 'plugins/BungeeTabListPlus_BukkitBridge-3.4.1-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: codecrafter47/bungeetablistplus/BukkitPlugin : Unsupported major.minor version 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:164)
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:307)
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:231)
	at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:256)
	at cpw.mods.fml.common.event.FMLServerAboutToStartEvent.<init>(FMLServerAboutToStartEvent.java:30)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:527)
	at cpw.mods.fml.common.LoaderState.getEvent(LoaderState.java:84)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:103)
	at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:807)
	at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:309)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:212)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:172)
	at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
Caused by: java.lang.UnsupportedClassVersionError: codecrafter47/bungeetablistplus/BukkitPlugin : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:443)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:360)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153)
	... 15 more
```
I believe this means wrong java version. 1.5.2 runs on Java 7, whats BTLP run on?

**Comment by CodeCrafter47** [comment]
You need Java 8 or higher. Actually the plugin should give you a nice error message telling you you need Java 8, not this ugly one. But it appears that is broken. I'm pretty sure 1.5.2 will run with Java 8 too. I'm not aware of any breaking changes there.

**Comment by Zilacon** [comment]
@CodeCrafter47 MCPC+ 1.6.4 was originally made for Java 7 and was even Java locked so you couldnt use it with Java 8 but weve patched it to remove that lock and it works fine with not only Java 8, but even OpenJ9.

1.5.2 MCPC+ however is a different story, we applied the same patch to it but whenever java 8 is used it fails to load any plugins and throws numerous errors with many mods. Causing the server to shutdown after startup.

So this work around could technically work for 1.6.4, but i dont think so for 1.5.2. Ill give it a shot on a 1.6.4 server.

**Comment by Zilacon** [comment]
Confirmed working on 1.6.4:
```
09-22 09:06:13 [INFO] [BungeeTabListPlus] Loading BungeeTabListPlus v3.4.1-SNAPSHOT
```

**Comment by Irgendwer01** [comment]
@Zilacon yes it was usally made for Java 7 but u can still use Java 8 with it all features there are compatible with it

**Comment by Zilacon** [comment]
@Irgendwer01 No, you cant. Like i said above our developers needed to remove the java lock from the software for 1.6.4 to get it to even consider running on java 8. Then it needed to be patched again to support OpenJ9. 1.5.2 MCPC+ will not work at all on java 8, and too much of it would need to be updated/patched to get it to do so.
