### ISSUE TITLE
Error in the console

### ISSUE THREAD

**Issue by assasin541** [CodeCrafter47/BungeeTabListPlus#603]
[21:48:55 WARN] [BungeeTabListPlus]: An unexpected error occurred: not active
java.lang.IllegalStateException: not active
        at de.codecrafter47.taboverlay.config.view.AbstractActiveElement.hasListener(AbstractActiveElement.java:61) ~[?:?]
        at de.codecrafter47.taboverlay.config.placeholder.GenericPlaceholder$GenericPlaceholderTextView.run(GenericPlaceholder.java:115) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649) ~[?:1.8.0_242]
        at java.util.Collections$SetFromMap.forEach(Collections.java:5530) ~[?:1.8.0_242]
        at de.codecrafter47.data.api.DataCache.updateValue(DataCache.java:39) ~[?:?]
        at codecrafter47.bungeetablistplus.managers.DataManager.lambda$updateIfNecessary$0(DataManager.java:136) ~[?:?]
        at codecrafter47.bungeetablistplus.util.ExceptionHandlingEventExecutor.run(ExceptionHandlingEventExecutor.java:42) ~[?:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:f029e94:unknown]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:f029e94:unknown]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:f029e94:unknown]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by CodeCrafter47** [comment]
This is a bug. Can you provide some more information, namely the following.
 * Which version of BungeeTabListPlus are you using.
 * Under which circumstances and how frequently does the issue occur.
 * The config (`default.yml`) using which the bug occurs.
