### ISSUE TITLE
An unexpected error occurred: Failed to run listener

### ISSUE THREAD

**Issue by andrewkm** [CodeCrafter47/BungeeTabListPlus#614]
WaterFall: Build 393
Paper: 1.16.4 Build 441
BungeeTabListPlus: 3.5.0 Build 1089
PremiumVanish: 2.6.3

Everytime I vanish or switch servers I get the following error in Bungee:
(This error only appears when vanishing, or switching servers while in vanish.)
```
[08:04:07] [BungeeTabListPlus Pool Thread #0/WARN] [BungeeTabListPlus]: An unexpected error occurred: Failed to run listener
java.lang.AssertionError: Failed to run listener
	at de.codecrafter47.data.api.DataCache.updateValue(DataCache.java:45) ~[?:?]
	at codecrafter47.bungeetablistplus.bridge.BukkitBridge.lambda$onDataReceived$4(BukkitBridge.java:388) ~[?:?]
	at codecrafter47.bungeetablistplus.util.ExceptionHandlingEventExecutor.run(ExceptionHandlingEventExecutor.java:42) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

Note, I recently added vanish suffixes (which work great!).

```
customPlaceholders:
  vanish_suffix: !conditional
    condition: ${player is_hidden}
    true: "&b[&bV&b]"
    false: ""
```

`playerComponent: {text: "${vanish_suffix}${player vault_prefix}${player name}", icon: "${player skin}", ping: "${player ping}"}`

TabList:
https://gist.githubusercontent.com/andrewkm/f8e16b9c3dc187bdb866f36ea966c6d3/raw/ffed0bf1274d013ca2272f44f1cc5853807a3dcc/gistfile1.txt

Result is:
https://i.imgur.com/2uxsHMa.png

Once again, result, and functionality is working great.
The console spam is quite heavy however.
Would love a fix for this.

**Comment by mibby** [comment]
@CodeCrafter47 I'm also able to confirm this issue being present in my environment.

Waterfall dev 394
BungeeTabListPlus dev 1090

```
[11:58:25] [Netty Worker IO Thread #1/INFO]: [mibby|/censored] <-> ServerConnector [server] has connected
[11:58:25] [Netty Worker IO Thread #1/WARN] [BungeeTabListPlus.mibby]: [mibby] Blocking Team Packet for Team LD_NoName, as it is incompatible with BungeeTabListPlus.
[11:58:30] [BungeeTabListPlus Pool Thread #0/WARN] [BungeeTabListPlus]: An unexpected error occurred: Failed to run listener
java.lang.AssertionError: Failed to run listener
	at de.codecrafter47.data.api.DataCache.updateValue(DataCache.java:45) ~[?:?]
	at codecrafter47.bungeetablistplus.bridge.BukkitBridge$BridgeData.lambda$reset$1(BukkitBridge.java:614) ~[?:?]
	at codecrafter47.bungeetablistplus.util.ExceptionHandlingEventExecutor.run(ExceptionHandlingEventExecutor.java:42) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:f2d67ca:394]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:f2d67ca:394]
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:f2d67ca:394]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by KingLego2006** [comment]
I recently encountered this issue as well, here is the message from my BungeeCord console

09:29:48 [INFO] [BungeeChat] JOIN > Lobby > KingLego2006: KingLego2006 has joined the network!
09:30:02 [INFO] [KingLego2006] <-> ServerConnector [Survival] has connected
09:30:03 [INFO] [BungeeChat] SWITCH > Survival > KingLego2006: KingLego2006 has moved to the Survival server!
09:30:03 [INFO] [KingLego2006] <-> DownstreamBridge <-> [Lobby] has disconnected
09:30:03 [WARNING] [BungeeTabListPlus] An unexpected error occurred: Failed to run listener
java.lang.AssertionError: Failed to run listener
    at de.codecrafter47.data.api.DataCache.updateValue(DataCache.java:45)
    at codecrafter47.bungeetablistplus.managers.DataManager.lambda$updateIfNecessary$0(DataManager.java:136)
    at codecrafter47.bungeetablistplus.util.ExceptionHandlingEventExecutor.run(ExceptionHandlingEventExecutor.java:42)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

I am running Version 3.5.0-SNAPSHOT with the Bukkit Bridge version 3.4.3 installed on all servers.  This didnt effect anything in my tablist at all, and it still functioned normally.

**Comment by KingLego2006** [comment]
> I recently encountered this issue as well, here is the message from my BungeeCord console
> 
> 09:29:48 [INFO] [BungeeChat] JOIN > Lobby > KingLego2006: KingLego2006 has joined the network!
> 09:30:02 [INFO] [KingLego2006] <-> ServerConnector [Survival] has connected
> 09:30:03 [INFO] [BungeeChat] SWITCH > Survival > KingLego2006: KingLego2006 has moved to the Survival server!
> 09:30:03 [INFO] [KingLego2006] <-> DownstreamBridge <-> [Lobby] has disconnected
> 09:30:03 [WARNING] [BungeeTabListPlus] An unexpected error occurred: Failed to run listener
> java.lang.AssertionError: Failed to run listener
> at de.codecrafter47.data.api.DataCache.updateValue(DataCache.java:45)
> at codecrafter47.bungeetablistplus.managers.DataManager.lambda$updateIfNecessary$0(DataManager.java:136)
> at codecrafter47.bungeetablistplus.util.ExceptionHandlingEventExecutor.run(ExceptionHandlingEventExecutor.java:42)
> at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
> at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> at java.lang.Thread.run(Unknown Source)
> 
> I am running Version 3.5.0-SNAPSHOT with the Bukkit Bridge version 3.4.3 installed on all servers. This didnt effect anything in my tablist at all, and it still functioned normally.

from what I can see, it happens when someone moves on/off of my Lobby server, but not every time...

**Comment by PrinceBunBun981** [comment]
Waterfall: Build 393
Paper: 1.16.4 Build 416
BungeeTabListPlus: 3.5.0 Build 1093

`[BungeeTabListPlus]: An unexpected error occurred: Failed to run listener
java.lang.AssertionError: Failed to run listener
        at de.codecrafter47.data.api.DataCache.updateValue(DataCache.java:45) ~[?:?]
        at codecrafter47.bungeetablistplus.managers.DataManager.lambda$updateIfNecessary$0(DataManager.java:136) ~[?:?]
        at codecrafter47.bungeetablistplus.util.ExceptionHandlingEventExecutor.run(ExceptionHandlingEventExecutor.java:42) ~[?:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_282]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]`
        
Same error as mentioned above in OP's message, though have narrowed it down to only happen when using the `!select` component (for me at least) It however will go away once the component is gone (or commented out)

**Comment by CodeCrafter47** [comment]
This is fixed now, if I'm not mistaken.

**Comment by andrewkm** [comment]
This is still broken @CodeCrafter47 
```
[09:10:34] [BungeeTabListPlus Pool Thread #0/WARN] [BungeeTabListPlus]: An unexpected error occurred: Failed to run listener
java.lang.AssertionError: Failed to run listener
	at de.codecrafter47.data.api.DataCache.updateValue(DataCache.java:45) ~[?:?]
	at codecrafter47.bungeetablistplus.bridge.BukkitBridge.lambda$onDataReceived$4(BukkitBridge.java:388) ~[?:?]
	at codecrafter47.bungeetablistplus.util.ExceptionHandlingEventExecutor.run(ExceptionHandlingEventExecutor.java:42) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9c49d76:414]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9c49d76:414]
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:9c49d76:414]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[09:11:11] [Netty Worker IO Thread #10/INFO]: [/85.226.111.218:52214|loowaa] -> UpstreamBridge has disconnected
```

**Comment by CodeCrafter47** [comment]
@andrewkm is this using the latest dev-build?

**Comment by CodeCrafter47** [comment]
I have updated the dev-build to provide more insight when this kind of error occurs. Could you run the latest dev-build and send me the error messages?

**Comment by andrewkm** [comment]
@CodeCrafter47 sorry for my late response, It's been hectic IRL and I've many negative news around the family.
Anyways, I am finally getting around to things again.

The error does indeed persist.
When vanishing with PremiumVanish the error is now as shown:

```
[09:00:15] [BungeeTabListPlus Pool Thread #0/WARN] [BungeeTabListPlus]: An unexpected error occurred: Failed to run listener
java.lang.AssertionError: Failed to run listener
	at de.codecrafter47.data.api.DataCache.updateValue(DataCache.java:45) ~[?:?]
	at codecrafter47.bungeetablistplus.bridge.BukkitBridge.lambda$onDataReceived$4(BukkitBridge.java:388) ~[?:?]
	at codecrafter47.bungeetablistplus.util.ExceptionHandlingEventExecutor.run(ExceptionHandlingEventExecutor.java:42) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.AssertionError: Failed to run listener
	at de.codecrafter47.data.api.DataCache.updateValue(DataCache.java:45) ~[?:?]
	at codecrafter47.bungeetablistplus.data.AbstractCompositeDataProvider$PlayerDataListener.run(AbstractCompositeDataProvider.java:57) ~[?:?]
	at de.codecrafter47.data.api.DataCache.updateValue(DataCache.java:42) ~[?:?]
	... 8 more
Caused by: java.lang.IllegalStateException: not active
	at de.codecrafter47.taboverlay.config.view.AbstractActiveElement.getListener(AbstractActiveElement.java:76) ~[?:?]
	at de.codecrafter47.taboverlay.config.placeholder.GenericPlaceholder$GenericPlaceholderToBooleanExpression.run(GenericPlaceholder.java:203) ~[?:?]
	at de.codecrafter47.data.api.DataCache.updateValue(DataCache.java:42) ~[?:?]
	at codecrafter47.bungeetablistplus.data.AbstractCompositeDataProvider$PlayerDataListener.run(AbstractCompositeDataProvider.java:57) ~[?:?]
	at de.codecrafter47.data.api.DataCache.updateValue(DataCache.java:42) ~[?:?]
	... 8 more
```

When unvanishing this is not present.
Plugin used is: https://www.spigotmc.org/resources/premiumvanish-stay-hidden-bungee-support.14404/

**Comment by KingLego2006** [comment]
> I have updated the dev-build to provide more insight when this kind of error occurs. Could you run the latest dev-build and send me the error messages?

I can look into it later, sorry also for late response

**Comment by KingLego2006** [comment]
> @CodeCrafter47 sorry for my late response, It's been hectic IRL and I've many negative news around the family.
> Anyways, I am finally getting around to things again.
> 
> The error does indeed persist.
> When vanishing with PremiumVanish the error is now as shown:
> 
> ```
> [09:00:15] [BungeeTabListPlus Pool Thread #0/WARN] [BungeeTabListPlus]: An unexpected error occurred: Failed to run listener
> java.lang.AssertionError: Failed to run listener
> 	at de.codecrafter47.data.api.DataCache.updateValue(DataCache.java:45) ~[?:?]
> 	at codecrafter47.bungeetablistplus.bridge.BukkitBridge.lambda$onDataReceived$4(BukkitBridge.java:388) ~[?:?]
> 	at codecrafter47.bungeetablistplus.util.ExceptionHandlingEventExecutor.run(ExceptionHandlingEventExecutor.java:42) ~[?:?]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
> 	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
> 	at java.lang.Thread.run(Thread.java:834) [?:?]
> Caused by: java.lang.AssertionError: Failed to run listener
> 	at de.codecrafter47.data.api.DataCache.updateValue(DataCache.java:45) ~[?:?]
> 	at codecrafter47.bungeetablistplus.data.AbstractCompositeDataProvider$PlayerDataListener.run(AbstractCompositeDataProvider.java:57) ~[?:?]
> 	at de.codecrafter47.data.api.DataCache.updateValue(DataCache.java:42) ~[?:?]
> 	... 8 more
> Caused by: java.lang.IllegalStateException: not active
> 	at de.codecrafter47.taboverlay.config.view.AbstractActiveElement.getListener(AbstractActiveElement.java:76) ~[?:?]
> 	at de.codecrafter47.taboverlay.config.placeholder.GenericPlaceholder$GenericPlaceholderToBooleanExpression.run(GenericPlaceholder.java:203) ~[?:?]
> 	at de.codecrafter47.data.api.DataCache.updateValue(DataCache.java:42) ~[?:?]
> 	at codecrafter47.bungeetablistplus.data.AbstractCompositeDataProvider$PlayerDataListener.run(AbstractCompositeDataProvider.java:57) ~[?:?]
> 	at de.codecrafter47.data.api.DataCache.updateValue(DataCache.java:42) ~[?:?]
> 	... 8 more
> ```
> 
> When unvanishing this is not present.
> Plugin used is: https://www.spigotmc.org/resources/premiumvanish-stay-hidden-bungee-support.14404/
> 
> Result and functionality as mentioned in original report is great and working.
> Just this darn error spam. :(

I dont have PremiumVanish on my network anywhere, and still get a listener error, i had it due to a !select component, similar to what @PrinceBunBun981 noted above.

**Comment by andrewkm** [comment]
Still getting this @CodeCrafter47 
Will it ever be addressed?
https://pastebin.com/raw/iC05dPmV

**Comment by CodeCrafter47** [comment]
I've just had a go at this. CodeCrafter47/minecraft-data-api@ae6d3f097ea33d10a9fd200e8f13f1fff5f27f59 should fix the issue. The fix is available in the [dev-builds](https://ci.codecrafter47.de/job/BungeeTabListPlus/).

**Comment by andrewkm** [comment]
This is finally fixed!
Many thanks! <3 clean console once more hurray!

**Comment by andrewkm** [comment]
I literally have to re-visit this ticket again to say how absolutely amazing it is that this was fixed!
It was absolute terror for months lmao. <3 Thanks again!
