### ISSUE TITLE
 Could not load plugins/BungeeTabListPlus

### ISSUE THREAD

**Issue by TheRealKraken** [CodeCrafter47/BungeeTabListPlus#615]
**So, I'm running a bungee cord server and for some reason, when I installed the plugin on all my servers, it installed correctly on all, except one server. Which is my hub server. I don't know If this means anything. When I restart the server in an attempt to install the plugin, I get the following error:**

```
 >[21:28:08] [Server thread/WARN]: Legacy plugin BungeeTabListPlus v3.4.3 does not specify an api-version.

>[21:28:08] [Server thread/ERROR]: Could not load 'plugins/BungeeTabListPlus-3.4.3.jar' in folder 'plugins'

org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/md_5/bungee/api/plugin/Plugin

at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]

at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]

at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]

at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:383) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]

at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:185) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]

at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]

at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/plugin/Plugin

at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_212]

at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_212]

at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_212]

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]

at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]

at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]

at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]

at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]

at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]

at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]

... 7 more 
```
**If anyone knows how to fix this, please let me know. It just won't install, I don't know if another plugin could possibly be interfering with it maybe? I have tried reinstalling it multiple times and also redownloading the plugin and installing that. It just won't work, I'm clueless.**

**Comment by Andre601** [comment]
BungeeTabListPlus is a **BungeeCord plugin**, meaning it can only be used on the BungeeCord Proxy.

For the spigot server would you use the BukkitBridge plugin, but it only is used for world/papi placeholders.

**Comment by TheRealKraken** [comment]
Ive tried installing that one too, i got the same error.

**Comment by Andre601** [comment]
You need the main plugin on the Proxy's `plugins` folder and the bridge one on the spigot's `plugins` folder.

The bridge plugin needs the main one on the proxy.

**Comment by TheRealKraken** [comment]
Yes, that is how i have it set up. It just wont install on the hub server. It installed fine on my other spigot servers and on my proxy server. Its just on this one, im not sure why.

**Comment by Andre601** [comment]
When the plugin doesn't work should there be an error in the proxy console.
Please provide the logs of your proxy. Prefferably through https://paste.helpch.at or https://gist.github.com.

**Comment by TheRealKraken** [comment]
nvm, I fixed it randomly. I just completely replaced the file again and that somehow worked :/
