### ISSUE TITLE
Using aegis, working on a premium and cracked user server.

### ISSUE THREAD

**Issue by TimkaEsT** [CodeCrafter47/BungeeTabListPlus#621]
[BungeeTabListPlus] An internal error occurred! Please send the following StackTrace to the developer in order to help resolving the problem
java.lang.AssertionError: Duplicate PostLoginEvent for player TimkaEsT
    at codecrafter47.bungeetablistplus.managers.TabViewManager.onPlayerJoin(TabViewManager.java:64)
    at codecrafter47.bungeetablistplus.listener.TabListListener.onPlayerJoin(TabListListener.java:45)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:29)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:402)
    at net.md_5.bungee.connection.InitialHandler.finnalyFinishLogin(InitialHandler.java:900)
    at net.md_5.bungee.connection.InitialHandler.lambda$finishLogin$3(InitialHandler.java:883)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by CodeCrafter47** [comment]
That is probably a bug in aegis. I don't think there's anything I can do about it.
