### ISSUE TITLE
Support for PremiumVanish levels

### ISSUE THREAD

**Issue by PrinceHatem** [CodeCrafter47/BungeeTabListPlus#651]
Hello,
PremiumVanish offers vanish levels where a player with a higher vanish level than your perm allows you to see would be vanished from you. This allows for Owners to vanish from admins and admins to vanish from mods and mods to vanish from helpers etc. However BTLP doesn't support it. So if I give my mod team the bungeetablist.seevanish perm then they will see all the higher players in the tablist (even though they don't see them in game)

I hope that since PremiumVanish is said to be supported, you can add support for their vanish levels. Thank you in advance

If you need more info, my discord is @PrinceHatem#0001

**Comment by XxMr1234GamerzxX** [comment]
expanding upon this premium vanish is not supported...... 

it seems to think supervanish is installed when it isnt.. btw this error is spammed every second on the bukkit bridge server console

```
[16:21:06 ERROR]: [BungeeTabListPlus] Unexpected exception
java.lang.NoClassDefFoundError: de/myzelyam/api/vanish/VanishAPI
        at de.codecrafter47.data.bukkit.supervanish.SuperVanishIsVanishedProvider.apply(SuperVanishIsVanishedProvider.java:28) ~[BungeeTabListPlus_BukkitBridge-3.4.4.jar:?]
        at de.codecrafter47.data.bukkit.supervanish.SuperVanishIsVanishedProvider.apply(SuperVanishIsVanishedProvider.java:25) ~[BungeeTabListPlus_BukkitBridge-3.4.4.jar:?]
        at de.codecrafter47.data.api.AbstractDataAccess.lambda$addProvider$0(AbstractDataAccess.java:30) ~[BungeeTabListPlus_BukkitBridge-3.4.4.jar:?]
        at de.codecrafter47.data.api.AbstractDataAccess.get(AbstractDataAccess.java:44) ~[BungeeTabListPlus_BukkitBridge-3.4.4.jar:?]
        at de.codecrafter47.data.bukkit.AbstractBukkitDataAccess.get(AbstractBukkitDataAccess.java:43) ~[BungeeTabListPlus_BukkitBridge-3.4.4.jar:?]
        at de.codecrafter47.data.api.JoinedDataAccess.get(JoinedDataAccess.java:40) ~[BungeeTabListPlus_BukkitBridge-3.4.4.jar:?]
        at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updatePlayerData(AbstractBridge.java:367) ~[BungeeTabListPlus_BukkitBridge-3.4.4.jar:?]
        at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updateData(AbstractBridge.java:302) ~[BungeeTabListPlus_BukkitBridge-3.4.4.jar:?]
        at codecrafter47.bungeetablistplus.bukkitbridge.BukkitBridge.lambda$onEnable$3(BukkitBridge.java:128) ~[BungeeTabListPlus_BukkitBridge-3.4.4.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) [patched_1.17.1.jar:git-Airplane-87]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [patched_1.17.1.jar:git-Airplane-87]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.17.1.jar:git-Airplane-87]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```
