### ISSUE TITLE
java.lang.IllegalStateException: BungeeTabListPlus not initialized

### ISSUE THREAD

**Issue by RMrenex** [CodeCrafter47/BungeeTabListPlus#660]
Hi,

I'm using the BungeeTablistPlus api in my plugin but when my connection event fires I get this error:

` Error dispatching event PostLoginEvent(player=RMrenex) to listener fr.derycube.tablist.tablist.PlayerLogin@13444fe
java.lang.IllegalStateException: BungeeTabListPlus not initialized
    at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
    at codecrafter47.bungeetablistplus.api.bungee.BungeeTabListPlusAPI.createCustomTablist(BungeeTabListPlusAPI.java:75)
    at fr.derycube.tablist.tablist.PlayerLogin.afterLogin(PlayerLogin.java:22)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:47)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:412)
    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:532)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.lang.Thread.run(Unknown Source)`

In my bungee.yml I have softDepends: ['BungeeTabListPlus']  
I specify that I use the api in my code but I don't have the BungeeTablistPlus plugin on my server.
My [pom.xml](https://pastebin.com/NTicY9qs)
I removed the provided scope for the dependency because I don't have the plugin on my server.
    
Server version : 1.8.8

**Comment by RMrenex** [comment]
My mistake
