### ISSUE TITLE
Failed to acquire data DataKey

### ISSUE THREAD

**Issue by PonyPC** [CodeCrafter47/BungeeTabListPlus#679]
11:19:10 [WARNING] [BungeeTabListPlus] Failed to acquire data DataKey(id=btlp:icon, scope=Scope(id=bungee:player), type=de.codecrafter47.data.api.TypeToken@578badab, parameter=null) from FarronEiffelt
java.lang.NoSuchMethodError: net.md_5.bungee.connection.LoginResult.getProperties()[Lnet/md_5/bungee/connection/LoginResult$Property;
	at codecrafter47.bungeetablistplus.util.IconUtil.getIconFromPlayer(IconUtil.java:36)
	at de.codecrafter47.data.api.AbstractDataAccess.lambda$addProvider$0(AbstractDataAccess.java:30)
	at de.codecrafter47.data.api.AbstractDataAccess.get(AbstractDataAccess.java:44)
	at de.codecrafter47.data.bungee.AbstractBungeeDataAccess.get(AbstractBungeeDataAccess.java:42)
	at de.codecrafter47.data.api.JoinedDataAccess.get(JoinedDataAccess.java:40)
	at codecrafter47.bungeetablistplus.managers.DataManager.updateData(DataManager.java:116)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by Andre601** [comment]
This should be fixed by the latest release.
Please update and let us know.

**Comment by PonyPC** [comment]
Thank you, it is fixed
