### ISSUE TITLE
NoSuchMethodError on player join

### ISSUE THREAD

**Issue by nhanledev** [CodeCrafter47/BungeeTabListPlus#680]
I run later waterfall til this day to support 1.19 with BungeeTabListPlus 3.5.0. When player join the  server, these exception throws on bungeecord server:

```
[14:28:05 ERROR] [BungeeTabListPlus]: An internal error occurred! Please send the following StackTrace to the developer in order to help resolving the problem
java.lang.NoSuchMethodError: 'java.lang.String[][] net.md_5.bungee.protocol.packet.PlayerListItem$Item.getProperties()'
        at codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler$PlayerListEntry.<init>(AbstractTabOverlayHandler.java:2619) ~[?:?]
        at codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler$PlayerListEntry.<init>(AbstractTabOverlayHandler.java:2610) ~[?:?]
        at codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler.onPlayerListPacket(AbstractTabOverlayHandler.java:241) ~[?:?]
        at codecrafter47.bungeetablistplus.protocol.AbstractPacketHandler.onPlayerListPacket(AbstractPacketHandler.java:40) ~[?:?]
        at codecrafter47.bungeetablistplus.handler.GetGamemodeLogic.onPlayerListPacket(GetGamemodeLogic.java:44) ~[?:?]
        at codecrafter47.bungeetablistplus.protocol.AbstractPacketHandler.onPlayerListPacket(AbstractPacketHandler.java:40) ~[?:?]
        at codecrafter47.bungeetablistplus.handler.RewriteLogic.onPlayerListPacket(RewriteLogic.java:93) ~[?:?]
        at codecrafter47.bungeetablistplus.protocol.PacketListener.decode(PacketListener.java:62) ~[?:?]
        at codecrafter47.bungeetablistplus.protocol.PacketListener.decode(PacketListener.java:32) ~[?:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-11062022.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e3ea:unknown]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Andre601** [comment]
Update to latest dev build
