### ISSUE TITLE
Teams chat spam

### ISSUE THREAD

**Issue by brainscript** [CodeCrafter47/BungeeTabListPlus#69]
My console gets spammed with:
```
Transformed packet Team(name=NTE1, mode=4, displayName=null, prefix=null, suffix
=null, nameTagVisibility=null, color=0, friendlyFire=0, players=[])
19:58:53 [WARNING] [BungeeTabListPlus] Scoreboard teams don't work with tab_size
 < 80.
```
My tabsize in the `config.yml` of **BungeeCord** is `80` and I enabled `AutoShrinkTabList` in the **tablist config**. After disconnecting from the proxy this error appeared:
```
19:59:37 [INFO] [brainscript] -> UpstreamBridge has disconnected
19:59:37 [SEVERE] [BungeeTabListPlus] An error occurred while querying data from
 BungeePerms. Make sure you have configured BungeePerms to use it's uuidPlayerDB
.
java.lang.NullPointerException
    at net.alpenblock.bungeeperms.PermissionsManager.getUser(PermissionsManager.
java:469)
    at codecrafter47.bungeetablistplus.managers.PermissionManager.getMainGroupFr
omBungeePerms(PermissionManager.java:94)
    at codecrafter47.bungeetablistplus.managers.PermissionManager.getMainGroup(P
ermissionManager.java:51)
    at codecrafter47.bungeetablistplus.config.TabListConfig.appliesTo(TabListCon
fig.java:187)
    at codecrafter47.bungeetablistplus.tablistproviders.ConfigTabListProvider.ap
pliesTo(ConfigTabListProvider.java:130)
    at codecrafter47.bungeetablistplus.managers.TabListManager.getTabListForPlay
er(TabListManager.java:99)
    at codecrafter47.bungeetablistplus.ResendThread.update(ResendThread.java:86)

    at codecrafter47.bungeetablistplus.ResendThread.run(ResendThread.java:63)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
19:59:37 [INFO] [brainscript] disconnected with: [Proxy] Lost connection to serv
er.
19:59:37 [INFO] [brainscript] <-> DownstreamBridge <-> [LOBBY] has disconnected
19:59:51 [SEVERE] Dec 29, 2015 7:59:51 PM net.md_5.bungee.event.EventBus post
WARNING: Error dispatching event PermissionCheckEvent(sender=brainscript, permis
sion=bungeetablistplus.seevanished, hasPermission=false) to listener net.alpenbl
ock.bungeeperms.platform.bungee.BungeeEventListener@753432a2
java.lang.NullPointerException
    at net.alpenblock.bungeeperms.PermissionsManager.getUser(PermissionsManager.
java:469)
    at net.alpenblock.bungeeperms.PermissionsChecker.hasPermOrConsoleOnServerInW
orld(PermissionsChecker.java:334)
    at net.alpenblock.bungeeperms.platform.bungee.BungeeEventListener.onPermissi
onCheck(BungeeEventListener.java:119)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:1
9)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:374
)
    at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:466)
    at codecrafter47.bungeetablistplus.managers.PermissionManager.hasPermission(
PermissionManager.java:315)
    at codecrafter47.bungeetablistplus.managers.PlayerManagerImpl.<init>(PlayerM
anagerImpl.java:47)
    at codecrafter47.bungeetablistplus.BungeeTabListPlus.constructPlayerManager(
BungeeTabListPlus.java:479)
    at codecrafter47.bungeetablistplus.ResendThread.update(ResendThread.java:94)

    at codecrafter47.bungeetablistplus.ResendThread.run(ResendThread.java:63)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```
I'm using **[NameTagEdit](https://www.spigotmc.org/resources/nametagedit.3836/)** to change the nametags of the players using the API.

**Comment by brainscript** [comment]
I now use a selfcoded little tablist plugin.
