### ISSUE TITLE
Error in BungeeCoord Console

### ISSUE THREAD

**Issue by R-Mule** [CodeCrafter47/BungeeTabListPlus#7]
An internal error occurred! Please send the following StackTrace to the developer in order to help resolving the problem
java.io.IOException: Server returned HTTP response code: 503 for URL: https://api.mojang.com/profiles/minecraft
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
    at codecrafter47.bungeetablistplus.managers.SkinManager.fetchUUID(SkinManager.java:87)
    at codecrafter47.bungeetablistplus.managers.SkinManager.access$300(SkinManager.java:47)
    at codecrafter47.bungeetablistplus.managers.SkinManager$SkinFetchTask.run(SkinManager.java:148)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

**Comment by CodeCrafter47** [comment]
Seems the plugin is hit by mojangs rate limits.
