### ISSUE TITLE
BungeeTablistPlus breaks on latest waterfall (#508/#509)

### ISSUE THREAD

**Issue by Erlpil** [CodeCrafter47/BungeeTabListPlus#700]
Hello,

BungeeTablistPlus breaks on latest waterfall (#508/#509)

Here is the stacktrace: [https://pastebin.com/raw/Vzz74iQi](https://pastebin.com/raw/Vzz74iQi)

Worked fine on Waterfall build #507, but then they added 1.19.3 support today, it broken on upgrade.

Please let me know if you need more info.

**Comment by fanmuchen** [comment]
Just to mention that same happens to the latest Bungeecord (1.19.3). It seems tablist function is significantly different on 1.19.3 compared to 1.19.2. Here's the bungeecord log: https://pastebin.com/9E2WU1H8

Please also find the change log in the bungeecord repository as it may help developers to catch up with the changes: https://github.com/SpigotMC/BungeeCord/commit/5467e3a8424fdc4b72a26fc35d9a0432333fa4b2

Looking forward to a solution :)

**Comment by Andre601** [comment]
> Same problem here. @CodeCrafter47 

No need to tag. He can and will see it.

**Comment by Phoenix616** [comment]
Might just need a rebuild as Bungee changed `int` to `Integer` there.

**Comment by andrewkm** [comment]
@Andre601 when the plug-in is broken, I tag.

**Comment by NathanAdhitya** [comment]
The newest dev builds seem to work on the newest Bungeecord with 1.19.3 support. Try checking that out as a temporary alternative to the stable builds.

**Comment by Phoenix616** [comment]
> ^It is confirmed that this is not the case. BungeeTabListPlus is as of this moment still broken and will not work with Bungeecord/Waterfall that is built to allow 1.19.3 compatibility.

You should really provide information about what issues you have when you claim that... otherwise it can't be fixed.

**Comment by Erlpil** [comment]
> > ^It is confirmed that this is not the case. BungeeTabListPlus is as of this moment still broken and will not work with Bungeecord/Waterfall that is built to allow 1.19.3 compatibility.
> 
> You should really provide information about what issues you have when you claim that... otherwise it can't be fixed.

This has been discussed in length on their Discord. The errors originally posted are still valid. More and more people are also reporting this issue there, even with the latest dev build.

**Comment by Phoenix616** [comment]
Well not everyone has access to some random Discord or can find a certain conversation days after. Providing all available information when posting publicly can be extremely helpful especially if other people could fix the issue too that weren't in that private conversation you mentioned.

**Comment by Andre601** [comment]
> Well not everyone has access to some random Discord or can find a certain conversation days after. Providing all available information when posting publicly can be extremely helpful especially if other people could fix the issue too that weren't in that private conversation you mentioned.

While on one hand I like the help you give, telling others what they should do on a project that isn't their own is not something you should do here. But that's beyond this issue's main topic, so let's stay on it.

The issue is known and CodeCrafter will work on it once he can find time (PRs are welcome tho if you guys can fix it yourself).

**Comment by Phoenix616** [comment]
> The issue is known and CodeCrafter will work on it once he can find time (PRs are welcome tho if you guys can fix it yourself).

Well I can't PR if I don't know what the issue is. I previously compiled against the latest bungee myself (which essentially is what the latest build should do too? I checked the jar though and it looks like it compiled against the old BungeeCord. I don.t think that can be fixed with a PR if the Jenkins build server is broken) and it works just fine with 1.19.3 for me so there must be a different one hence why I felt that more information was needed.

I'm sorry I didn't formulate that in a way that made my goal to get that information and why clear.

**Comment by Andre601** [comment]
CodeCrafter pushed an update.
Testing it is appreciated: https://ci.codecrafter47.de/job/BungeeTabListPlus/

Notes from the Discord:

What is not tested:
 * Using the latest BungeeCord and older spigot or client versions. I expect this works fine.
 * Using an older BungeeCord without 1.19.3 support. I expect that this will not work. If that is the case, then future versions of the plugin might print a warning and refuse to start.
 * Not using ip-forwarding (this is probably fine)
 * Using ViaVersion on BungeeCord with a 1.19.3 spigot and 1.7.10 client. I have no idea if this will work.

What won't work:
 * Using Geyser. I plan to look into that next weekend.

**Comment by broken1arrow** [comment]
The version on the link seams to fix the issue, I also tested 1.18.2 and that works too.

**Comment by CodeZhangBorui** [comment]
Same problem here, start at line 103. [pastebin.com/BXg9pmMm](https://pastebin.com/BXg9pmMm)

**Comment by broken1arrow** [comment]
> Same problem here, start at line 103. See full log at [pastebin.com/BXg9pmMm](https://pastebin.com/BXg9pmMm)
> 
> ```
> [10:07:14] [Netty Worker IO Thread #3/ERROR] [BungeeTabListPlus]: An internal error occurred! Please send the following StackTrace to the developer in order to help resolving the problem
> java.lang.NoSuchMethodError: 'int net.md_5.bungee.protocol.packet.PlayerListItem$Item.getGamemode()'
> 	at codecrafter47.bungeetablistplus.handler.GetGamemodeLogic.onPlayerListPacket(GetGamemodeLogic.java:40) ~[?:?]
> 	at codecrafter47.bungeetablistplus.protocol.AbstractPacketHandler.onPlayerListPacket(AbstractPacketHandler.java:40) ~[?:?]
> 	at codecrafter47.bungeetablistplus.handler.RewriteLogic.onPlayerListPacket(RewriteLogic.java:101) ~[?:?]
> 	at codecrafter47.bungeetablistplus.protocol.PacketListener.decode(PacketListener.java:62) ~[?:?]
> 	at codecrafter47.bungeetablistplus.protocol.PacketListener.decode(PacketListener.java:32) ~[?:?]
> 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> ```

What version do you use?

**Comment by CodeZhangBorui** [comment]
> > Same problem here, start at line 103. See full log at [pastebin.com/BXg9pmMm](https://pastebin.com/BXg9pmMm)
> 
> What version do you use?

Waterfall version git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510 by md_5

**Comment by broken1arrow** [comment]
> > > Same problem here, start at line 103. See full log at [pastebin.com/BXg9pmMm](https://pastebin.com/BXg9pmMm)
> > 
> > 
> > What version do you use?
> 
> Waterfall version git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510 by md_5

I mean the plugin. Because last dev solve this issue.

**Comment by CodeZhangBorui** [comment]
> > > > Same problem here, start at line 103. See full log at [pastebin.com/BXg9pmMm](https://pastebin.com/BXg9pmMm)
> > > 
> > > 
> > > What version do you use?
> > 
> > 
> > Waterfall version git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510 by md_5
> 
> I mean the plugin. Because last dev solve this issue.

I'm sorry that I used the old version (3.5.2) to test, I've downloaded the lastest dev build and solved this problem :)
