### ISSUE TITLE
Nothing works except the footer and header.

### ISSUE THREAD

**Issue by khr245** [CodeCrafter47/BungeeTabListPlus#709]
I installed and ran BungeeTabListPlus on Waterfall and got the following error: "Tabs are not displayed except for the header and footer. What should I do?

Server Plugin Version
* BungeeTabListPlus version 3.5.2
* waterfall-1.19-510
* Vanilla Server PeparMC 1.19.2
* Lobby Server PeparMC 1.12.2

` [21:35:44] [Netty Worker IO Thread #1/ERROR] [BungeeTabListPlus]: An internal error occurred! Please send the following StackTrace to the developer in order to help resolving the problem
java.lang.NoSuchMethodError: 'int net.md_5.bungee.protocol.packet.PlayerListItem$Item.getGamemode()'
	at codecrafter47.bungeetablistplus.handler.GetGamemodeLogic.onPlayerListPacket(GetGamemodeLogic.java:40) ~[?:?]
	at codecrafter47.bungeetablistplus.protocol.AbstractPacketHandler.onPlayerListPacket(AbstractPacketHandler.java:40) ~[?:?]
	at codecrafter47.bungeetablistplus.handler.RewriteLogic.onPlayerListPacket(RewriteLogic.java:101) ~[?:?]
	at codecrafter47.bungeetablistplus.protocol.PacketListener.decode(PacketListener.java:62) ~[?:?]
	at codecrafter47.bungeetablistplus.protocol.PacketListener.decode(PacketListener.java:32) ~[?:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
[21:35:44] [Netty Worker IO Thread #1/ERROR] [BungeeTabListPlus]: An internal error occurred! Please send the following StackTrace to the developer in order to help resolving the problem
java.lang.NoSuchMethodError: 'int net.md_5.bungee.protocol.packet.PlayerListItem$Item.getGamemode()'
	at codecrafter47.bungeetablistplus.handler.GetGamemodeLogic.onPlayerListPacket(GetGamemodeLogic.java:40) ~[?:?]
	at codecrafter47.bungeetablistplus.protocol.AbstractPacketHandler.onPlayerListPacket(AbstractPacketHandler.java:40) ~[?:?]
	at codecrafter47.bungeetablistplus.handler.RewriteLogic.onPlayerListPacket(RewriteLogic.java:101) ~[?:?]
	at codecrafter47.bungeetablistplus.protocol.PacketListener.decode(PacketListener.java:62) ~[?:?]
	at codecrafter47.bungeetablistplus.protocol.PacketListener.decode(PacketListener.java:32) ~[?:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
[21:35:45] [Netty Worker IO Thread #1/WARN] [io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler$$Lambda$1127/0x000000084078c440@5c9ab8e4
java.lang.NoSuchMethodError: 'void net.md_5.bungee.protocol.packet.PlayerListItem$Item.setPing(int)'
	at codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler$CustomContentTabOverlayHandler.update(AbstractTabOverlayHandler.java:1992) ~[?:?]
	at codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler.update(AbstractTabOverlayHandler.java:529) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
[21:35:46] [Netty Worker IO Thread #1/WARN] [io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler$$Lambda$1127/0x000000084078c440@5c9ab8e4
java.lang.NoSuchMethodError: 'void net.md_5.bungee.protocol.packet.PlayerListItem$Item.setPing(int)'
	at codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler$CustomContentTabOverlayHandler.update(AbstractTabOverlayHandler.java:2035) ~[?:?]
	at codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler.update(AbstractTabOverlayHandler.java:529) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
[21:35:48] [Netty Worker IO Thread #1/WARN] [io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler$$Lambda$1127/0x000000084078c440@5c9ab8e4
java.lang.NoSuchMethodError: 'void net.md_5.bungee.protocol.packet.PlayerListItem$Item.setPing(int)'
	at codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler$CustomContentTabOverlayHandler.update(AbstractTabOverlayHandler.java:1992) ~[?:?]
	at codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler.update(AbstractTabOverlayHandler.java:529) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.19-510.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
	at java.lang.Thread.run(Thread.java:829) ~[?:?] `

**Comment by Andre601** [comment]
1. Please use a paste site to share errors. Reading them like that is awful and not really good.
2. Use the latest dev build from the CI and see if that solves your issue: https://ci.codecrafter47.de/job/BungeeTabListPlus/

**Comment by khr245** [comment]
Sorry about the code.
I have resolved the issue with the Tab display, but BungeeOnlineTime is not showing up. Is this a snapshot specific issue?

Version : BungeeOnlineTime 8.3

<img width="810" alt="スクリーンショット 2023-01-02 8 06 51" src="https://user-images.githubusercontent.com/91612483/210187042-33babe17-fee7-45ca-ba21-f55c308af77b.png">
