### ISSUE TITLE
Bungee errors on server disconnect.

### ISSUE THREAD

**Issue by andrewkm** [CodeCrafter47/BungeeTabListPlus#730]
Paper 1.20.1 Build 196
BungeeTabListPlus compiled against latest https://github.com/CodeCrafter47/BungeeTabListPlus/commit/a05beada9f8bf0904085637ccc0aa2ec3ddc8fd7
No ViaVersion on bungee, only on backend servers.

Using a 1.20.2 client on the above 1.20.1 latest paper build causes the following error in bungee console:
```
[13:19:43] [Netty Worker IO Thread #17/WARN] [io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: codecrafter47.bungeetablistplus.handler.NewTabOverlayHandler$$Lambda/0x000002543ba16000@4360973c
java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.protocol.MinecraftEncoder.getProtocol()" because the return value of "io.netty.channel.ChannelPipeline.get(java.lang.Class)" is null
	at net.md_5.bungee.netty.ChannelWrapper.getEncodeProtocol(ChannelWrapper.java:51) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4d5746a:544]
	at net.md_5.bungee.UserConnection.sendPacketQueued(UserConnection.java:194) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4d5746a:544]
	at codecrafter47.bungeetablistplus.handler.NewTabOverlayHandler.sendPacket(NewTabOverlayHandler.java:189) ~[?:?]
	at codecrafter47.bungeetablistplus.handler.NewTabOverlayHandler.access$700(NewTabOverlayHandler.java:53) ~[?:?]
	at codecrafter47.bungeetablistplus.handler.NewTabOverlayHandler$CustomContentTabOverlayHandler.onDeactivated(NewTabOverlayHandler.java:703) ~[?:?]
	at codecrafter47.bungeetablistplus.handler.NewTabOverlayHandler$AbstractContentOperationModeHandler.invalidate(NewTabOverlayHandler.java:393) ~[?:?]
	at codecrafter47.bungeetablistplus.handler.NewTabOverlayHandler.update(NewTabOverlayHandler.java:356) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4d5746a:544]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4d5746a:544]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4d5746a:544]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4d5746a:544]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4d5746a:544]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4d5746a:544]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
```
I notice there's another issue open that mentioned this error: https://github.com/CodeCrafter47/BungeeTabListPlus/issues/727
However as the issue is targeted towards kicking players, figured I'd make this post as well.

**Comment by andrewkm** [comment]
Fixed.
