### ISSUE TITLE
1.8 client crash (possible <1.13)

### ISSUE THREAD

**Issue by andreasdc** [CodeCrafter47/BungeeTabListPlus#738]
The latest version crashes 1.8 client and I guess all below 1.13
[12:05:37] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "a.b()" because the return value of "aul.l()" is null
	at avo.a(SourceFile:276) ~[minecraft-1.8.8-client.jar:?]
	at bfk.a(SourceFile:1021) ~[minecraft-1.8.8-client.jar:?]
	at ave.av(SourceFile:915) ~[minecraft-1.8.8-client.jar:?]
	at ave.a(SourceFile:325) [minecraft-1.8.8-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [minecraft-1.8.8-client.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

**Comment by Andre601** [comment]
Nothing in that stacktrace even remotely hints at BTLP being the issue, so what makes you think that?

**Comment by andreasdc** [comment]
> Nothing in that stacktrace even remotely hints at BTLP being the issue, so what makes you think that?

Because I checked that and I'm 100% sure.

**Comment by Andre601** [comment]
That doesn't proof anything.

This stacktrace doesn't make sense for a proxy, so I assume it's from your client logs?
I then want to say to please check your proxy logs for errors.

**Comment by andreasdc** [comment]
It is client crash. No errors on the proxy. I am 100% sure that it's BTLP's issue.

**Comment by Andre601** [comment]
Without any errors on proxy by btlp I doubt it is.

Errors caused by plugins on a proxy usually also show errors.

Please share your full latest.log through https://mclo.gs

**Comment by andreasdc** [comment]
I already told you, if you still don't believe me, you can check that by yourself. Sending wrong data to the client will result in a client crash, not plugin side error.

**Comment by Andre601** [comment]
As long as you're not providing any data to work with (proxy type and build, client version, etc.) we can't and won't help.
You are expected to give the least amount of work here.

So, instead of excuses, just provide the logs I asked you for already.

**Comment by andreasdc** [comment]
The latest bungeecord. The lastest BTLP. Have any tablist. Join with 1.8 and probably any version below 1.13. You get the crash. If you need more, check that by yourself, I assured you more than 3 times.

**Comment by Andre601** [comment]
And I told you 3 times now to give the logs of the proxy because client logs do absolutely nothing for us.

Also, make sure to join with latest 1.8 (1.8.9 iirc) since there were major changes between it and older 1.8 versions.

**Comment by andreasdc** [comment]
I told you what happens, I told you because of what, I already gave you everything that you wanted. I can't wait for the fix so I can update BTLP and bungee again. 🚀

**Comment by Andre601** [comment]
You didn't give everything I asked for...

I write it a final time and in caps so you hopefully get it:
GIVE US THE LATEST.LOG OF YOUR BUNGEECORD PROXY.

BTLP is a plugin, so we needs proxy logs for info.
Client logs won't help us here, and proxy logs may contain stuff you think is useless while it isn't.

Like in all honesty, stop acting like you know what we need here.

**Comment by andreasdc** [comment]
I don't have interest in talking with an ignorant. I told you everything, if you want more you can download and test it.

**Comment by Andre601** [comment]
> I don't have interest in talking with an disrespectful ignorant.

Ironic that this comes from someone refusing to do what is a literal copy-paste job here.

**Comment by andreasdc** [comment]
That's great, but you literally have everything that you wanted. 
This is the whole error in the proxy. 
username disconnected with: NativeIoException : recvAddress(..) failed: Connection reset by peer
Happy to help, can't wait for the fix

**Comment by andrewkm** [comment]
Someone close this dumb report.
The kid provides zero actual proxy/plugin logs and is now spamming in unrelated issues #735.

**Comment by andreasdc** [comment]
> Someone close this dumb report. The kid provides zero actual proxy/plugin logs and is now spamming in unrelated issues #735.

Very intelligent creature we have here. Let's find you a reward for this awesome achievement, but let's summarize you.
"dumb report" - solid bug that crashes the clients and make the server unplayable for <1.13 versions
"The kid" - older than you.
"zero actual proxy/plugin logs" - I provided the errors, other than that you don't see anything, only crashes on the client side.
" now spamming in unrelated issues" - it is actually the same error, just modified.
BTW Any chance for getting this fixed today?

**Comment by andrewkm** [comment]
> > Someone close this dumb report. The kid provides zero actual proxy/plugin logs and is now spamming in unrelated issues #735.
> 
> Very intelligent creature we have here. Let's find you a reward for this awesome achievement, but let's summarize you. "dumb report" - solid bug that crashes the clients and make the server unplayable for <1.13 versions "The kid" - older than you. "zero actual proxy/plugin logs" - I provided the errors, other than that you don't see anything, only crashes on the client side. " now spamming in unrelated issues" - it is actually the same error, just modified. BTW Any chance for getting this fixed today?

More incoherent rambling that once again provides no proxy logs, and no server side logs.

**Comment by andreasdc** [comment]
> > > Someone close this dumb report. The kid provides zero actual proxy/plugin logs and is now spamming in unrelated issues #735.
> > 
> > 
> > Very intelligent creature we have here. Let's find you a reward for this awesome achievement, but let's summarize you. "dumb report" - solid bug that crashes the clients and make the server unplayable for <1.13 versions "The kid" - older than you. "zero actual proxy/plugin logs" - I provided the errors, other than that you don't see anything, only crashes on the client side. " now spamming in unrelated issues" - it is actually the same error, just modified. BTW Any chance for getting this fixed today?
> 
> More incoherent rambling that once again provides no proxy logs, and no server side logs.

No point in dicussing with you if you can't even read, greetings.

**Comment by andrewkm** [comment]
I can assure you, your issue will **never** be solved without:

Environment information.
Server version/build info.
Plugin version/build info.
Full logs.
Full reproduction steps.
etc.

Zero effort will always equal zero help, thus this issue will certainly go unnoticed for months to come.
If you provided the relevant information we would be willing to help and I'd gladly try to reproduce, but it seems you are not capable of effort in that regard.

I shall take my leave, farewell. :)

**Comment by andreasdc** [comment]
> I can assure you, your issue will **never** be solved without:
> 
> * Environment information.
> * Server version/build info.
> * Plugin version/build info.
> * Full logs.
> * Full reproduction steps.
> * etc.
> 
> Zero effort will always equal zero help, thus this issue will certainly go unnoticed for **months** to come. If you provided the relevant information we would be willing to help and I'd gladly try to reproduce, but it seems you are not capable of effort in that regard.
> 
> I shall take my leave, farewell. :)

Great, till the time you will learn how to read this issue will be fixed, you can go waste your useless energy somewhere else.

**Comment by andreasdc** [comment]
> The latest bungeecord. The lastest BTLP. Have any tablist. Join with 1.8 and probably any version below 1.13. You get the crash. If you need more, check that by yourself, I assured you more than 3 times. No errors on the proxy, I gave you crash from the client. Probably here and maybe in the other places you need to check the protocol version and send either the string or the BaseComponent. https://github.com/CodeCrafter47/BungeeTabListPlus/blob/9c56d1b048ebff69837bf402025838690b8d5674/bungee/src/main/java/codecrafter47/bungeetablistplus/handler/AbstractLegacyTabOverlayHandler.java#L437C1-L437C1

Here is everything is needed. I'm not going to discuss anything else.

**Comment by NEZNAMY** [comment]
At this point the best thing to do would be for Mr. CodeCrafter to go to this user's profile a press "block user". They will no longer be able to comment or open any new issues.

**Comment by andreasdc** [comment]
You really think there is something more needed in this issue or you are just trolling?

**Comment by Andre601** [comment]
> You really think there is something more needed in this issue or you are just trolling?

The irony of that comment is beautiful

**Comment by andreasdc** [comment]
> > You really think there is something more needed in this issue or you are just trolling?
> 
> The irony of that comment is beautiful

Ok, you don't need to answer anything more :D There is second possibility, but I don't want to spam and insult you. You literally have everything that you wanted, everything that is possible, if you think otherwise I don't want to discuss and convince you.

**Comment by MacTh3Mac** [comment]
Resolved by PR #741  - @andreasdc  I would suggest closing this issue and waiting for the PR to be merged from Issue #739  which contains the info required to resolve the bug.

**Comment by andreasdc** [comment]
> Resolved by PR #741 - @andreasdc I would suggest closing this issue and waiting for the PR to be merged from Issue #739 which contains the info required to resolve the bug.

I have this error when building, could you share a jar?
Could not determine the dependencies of task ':BungeeTabListPlus:shadowJar'.
> Could not resolve all dependencies for configuration ':BungeeTabListPlus:runtimeClasspath'.
   > Could not find de.codecrafter47.taboverlay:taboverlaycommon-config:1.0-SNAPSHOT.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
       - https://nexus.codecrafter47.dyndns.eu/content/repositories/public/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://nexus.codecrafter47.dyndns.eu/content/repositories/public/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
       - https://repo.codemc.org/repository/maven-public/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://repo.codemc.org/repository/maven-public/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
       - https://repo.md-5.net/content/repositories/snapshots/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://repo.md-5.net/content/repositories/snapshots/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
       - https://hub.spigotmc.org/nexus/content/repositories/snapshots/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://hub.spigotmc.org/nexus/content/repositories/snapshots/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
       - https://papermc.io/repo/repository/maven-snapshots/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://papermc.io/repo/repository/maven-snapshots/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
       - https://repo.spongepowered.org/maven/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://repo.spongepowered.org/maven/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
       - https://jitpack.io/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
       - https://oss.sonatype.org/content/repositories/snapshots/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://oss.sonatype.org/content/repositories/snapshots/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
     Required by:
         project :BungeeTabListPlus > project :bungee-plugin
