### ISSUE TITLE
eceived ServerSwitchEvent for non-existent player

### ISSUE THREAD

**Issue by andreasdc** [CodeCrafter47/BungeeTabListPlus#740]
Happened after client disconnecter quickly after logging in.
```
[19:05:14] [Netty Worker IO Thread #13/INFO]: [AllahFinder] disconnected with: NativeIoException : recvAddress(..) failed: Connection reset by peer
[19:05:14] [Netty Worker IO Thread #13/WARN]: Error dispatching event ServerConnectedEvent(player=player, server=net.md_5.bungee.ServerConnection@77cbc8c3) to listener codecrafter47.bungeetablistplus.managers.TabViewManager@312afbc7
java.lang.AssertionError: Received ServerSwitchEvent for non-existent player player
	at codecrafter47.bungeetablistplus.managers.TabViewManager.onServerConnected(TabViewManager.java:90) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:17) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:53) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:511) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at net.md_5.bungee.ServerConnector.handleLogin(ServerConnector.java:239) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:226) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at net.md_5.bungee.protocol.packet.Login.handle(Login.java:283) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:140) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[x.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:289f726:unknown]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by andrewkm** [comment]
Report once again missing standard information.

Environment, versions, etc.

**Comment by andrewkm** [comment]
Experiencing the same thing here @CodeCrafter47 
https://pastebin.com/raw/qMUPQPjw
