### ISSUE TITLE
Flamecord / Waterfall Error 

### ISSUE THREAD

**Issue by Puebl090** [CodeCrafter47/BungeeTabListPlus#745]
[16:38:54 WARN] [io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: codecrafter47.bungeetablistplus.handler.NewTabOverlayHandler$$Lambda$489/0x00007f5fa9505050@3ea4e01e
java.lang.NoSuchMethodError: 'void net.md_5.bungee.protocol.packet.Team.setDisplayName(java.lang.String)'
        at codecrafter47.bungeetablistplus.handler.NewTabOverlayHandler.createPacketTeamCreate(NewTabOverlayHandler.java:1239) ~[?:?]
        at codecrafter47.bungeetablistplus.handler.NewTabOverlayHandler.access$1900(NewTabOverlayHandler.java:55) ~[?:?]
        at codecrafter47.bungeetablistplus.handler.NewTabOverlayHandler$CustomContentTabOverlayHandler.createTeamsIfNecessary(NewTabOverlayHandler.java:676) ~[?:?]
        at codecrafter47.bungeetablistplus.handler.NewTabOverlayHandler$CustomContentTabOverlayHandler.onActivated(NewTabOverlayHandler.java:667) ~[?:?]
        at codecrafter47.bungeetablistplus.handler.NewTabOverlayHandler.update(NewTabOverlayHandler.java:356) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:aa6d62a:unknown]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:aa6d62a:unknown]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:aa6d62a:unknown]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:aa6d62a:unknown]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:aa6d62a:unknown]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:aa6d62a:unknown]
        at java.lang.Thread.run(Thread.java:840) [?:?]

**Comment by Andre601** [comment]
Use latest dev build please before reporting stuff.

**Comment by Puebl090** [comment]
i used the latest dev build

**Comment by Andre601** [comment]
That can't be true since the error was reported by other people too and using the latest dev build fixed it for them.
