### ISSUE TITLE
waterfall-1.20-556 doesn't work for 1.20.3 and 1.20.4

### ISSUE THREAD

**Issue by andfont** [CodeCrafter47/BungeeTabListPlus#747]
When you try to connect these versions it gives this error. I have tried waterfall-1.20-556 and waterfall-1.20-555 and the same thing happens.
 Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: z: Non [a-z0-9/._-] character in path of location: minecraft: BTLP633d1190 00

**Comment by andfont** [comment]
my server is 1.19.2 paper

**Comment by andfont** [comment]
I am using the development version and nothing happens in all versions of the error. greetings

**Comment by andfont** [comment]
In all cases I USE THE DEVELOPMENT VERSION but it is impossible nothing works.

BUNGECORD:

with BungeeCord-1779 I have these other errors:
Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: z: Non [a-z0-9/._-] character in path of location: minecraft: BTLP633d1190 00


WATERFALL:
with waterfall-1.20-556 and waterfall-1.20-555 gives these errors:
My server is 1.19.2 and 1.20.2 paper


[12:13:18 WARN] [BungeeTabListPlus.andfont]: [andfont] Cannot correctly update tablist for player andfont
The client and server versions do not match. Client < 1.19.3, server >= 1.19.3.
Use ViaVersion on the spigot server for the best experience.


[12:13:54 WARN]: Error dispatching event ServerConnectedEvent(player=andfont, server=net.md_5.bungee.ServerConnection@7385ddf6) to listener me.woder.MCBbungee.MCBbungee@59096b66
java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.protocol.MinecraftEncoder.getProtocol()" because the return value of "io.netty.channel.ChannelPipeline.get(java.lang.Class)" is null
        at net.md_5.bungee.netty.ChannelWrapper.getEncodeProtocol(ChannelWrapper.java:51) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at net.md_5.bungee.ServerConnection.sendPacketQueued(ServerConnection.java:48) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at net.md_5.bungee.ServerConnection.sendData(ServerConnection.java:70) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at me.woder.MCBbungee.MCBbungee.onServerSwitch(MCBbungee.java:65) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:467) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at net.md_5.bungee.ServerConnector.handleLogin(ServerConnector.java:234) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:854) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at net.md_5.bungee.protocol.packet.Login.handle(Login.java:283) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:124) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556]
        at java.lang.Thread.run(Thread.java:833) [?:?]
		
		
		
[12:26:15 WARN]: Error dispatching event ServerConnectedEvent(player=andfont, server=net.md_5.bungee.ServerConnection@60e19cc3) to listener me.woder.MCBbungee.MCBbungee@59096b66
java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.protocol.MinecraftEncoder.getProtocol()" because the return value of "io.netty.channel.ChannelPipeline.get(java.lang.Class)" is null
        at net.md_5.bungee.netty.ChannelWrapper.getEncodeProtocol(ChannelWrapper.java:51) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.ServerConnection.sendPacketQueued(ServerConnection.java:48) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.ServerConnection.sendData(ServerConnection.java:70) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at me.woder.MCBbungee.MCBbungee.onServerSwitch(MCBbungee.java:65) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:467) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.ServerConnector.handleLogin(ServerConnector.java:233) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:841) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.protocol.packet.Login.handle(Login.java:283) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:124) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by PrinceBunBun981** [comment]
I see you may be using ViaVersion on the proxy based on this error "Use ViaVersion on the spigot server for the best experience."

ViaVersion is not supported on the proxy when using this plugin, you will need to install it on each instance instead. If it is **not** being used on the proxy, please give some more details about the server setup (e.g. plugins and versions)

**Comment by andfont** [comment]
Hello friend, I have to use viaversion in the proxy to avoid failures and player access problems. If I don't use it as before, many people had disconnection problems. Thank you and I await the patch solution to the complement. greetings,

**Comment by PrinceBunBun981** [comment]
The only error I see that is from BungeeTabListPlus itself is from your previous comment:
> [12:13:18 WARN] [BungeeTabListPlus.andfont]: [andfont] Cannot correctly update tablist for player andfont
> The client and server versions do not match. Client < 1.19.3, server >= 1.19.3.
> Use ViaVersion on the spigot server for the best experience.

Everything else seems to be from a plugin called [MCBbungee](https://www.spigotmc.org/resources/mcbbungee-announce-when-people-switch-servers.177/). There's nothing that we can patch for that plugin as it isn't BTLP. As I said before, using ViaVersion on the proxy is **not** supported by BTLP, therefor a patch won't be made to fix it.
