### ISSUE TITLE
Update for Waterfall 1.20.4?

### ISSUE THREAD

**Issue by JuergenUniVie** [CodeCrafter47/BungeeTabListPlus#748]
Will there be an update in the foreseeable future so that BTLP is also compatible with the current Waterfall versions?

-----
[09:04:27 WARN] [io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: codecrafter47.bungeetablistplus.handler.NewTabOverlayHandler$$Lambda$2854/0x0000000801d8dec0@1ad79bf
java.lang.NoSuchMethodError: 'void net.md_5.bungee.protocol.packet.Team.setDisplayName(net.md_5.bungee.api.chat.BaseComponent)'
        at codecrafter47.bungeetablistplus.handler.NewTabOverlayHandler.createPacketTeamCreate(NewTabOverlayHandler.java:1258) ~[?:?]
        at codecrafter47.bungeetablistplus.handler.NewTabOverlayHandler.access$2100(NewTabOverlayHandler.java:58) ~[?:?]
        at codecrafter47.bungeetablistplus.handler.NewTabOverlayHandler$CustomContentTabOverlayHandler.createTeamsIfNecessary(NewTabOverlayHandler.java:689) ~[?:?]
        at codecrafter47.bungeetablistplus.handler.NewTabOverlayHandler$CustomContentTabOverlayHandler.onActivated(NewTabOverlayHandler.java:680) ~[?:?]
        at codecrafter47.bungeetablistplus.handler.NewTabOverlayHandler.update(NewTabOverlayHandler.java:367) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[waterfall-1.20-557.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e2b9b5e:557]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[waterfall-1.20-557.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e2b9b5e:557]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[waterfall-1.20-557.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e2b9b5e:557]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[waterfall-1.20-557.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e2b9b5e:557]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.20-557.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e2b9b5e:557]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.20-557.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e2b9b5e:557]
        at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by PrinceBunBun981** [comment]
Hey,

Try updating to use the [latest dev build](https://ci.codecrafter47.de/job/BungeeTabListPlus/lastSuccessfulBuild/) and see if that fixes the issue. The latest build is newer despite the version being behind Spigot.
