### ISSUE TITLE
BungeeCord uses BungeeTabListPlus to report errors.

### ISSUE THREAD

**Issue by guojiaqiang123** [CodeCrafter47/BungeeTabListPlus#751]
BungeeCord with build sequence 1786 is used, load the BungeeTabListPlus.jar plugin in the plugins folder.
When a player enters the server the console keeps brushing the warning

A task raised an exception. Task: codecrafter47.bungeetablistplus.handler.NewTabOverlayHandler$$Lambda$442/0x0000000800f93908@11add290
java.lang.NoSuchMethodError: 'void net.md_5.bungee.protocol.packet.PlayerListItem$Item.setDisplayName(java.lang.String)'
    at codecrafter47.bungeetablistplus.handler.NewTabOverlayHandler$CustomContentTabOverlayHandler.update(NewTabOverlayHandler.java:742)
    at codecrafter47.bungeetablistplus.handler.NewTabOverlayHandler.update(NewTabOverlayHandler.java:359)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Andre601** [comment]
Please use the latest dev build. The version is incorrect, but it is the latest build that should fix this issue.
