### ISSUE TITLE
Log Spam

### ISSUE THREAD

**Issue by Obatunde** [CodeCrafter47/BungeeTabListPlus#76]
Hi I am loving this mod, but it is creating a huge amount of spam in my log files:
Just a small section reads like this:

earth2me/essentials/User; from class codecrafter47.bungeetablistplus.data.essentials.EssentialsIsVanishedProvider
    at codecrafter47.bungeetablistplus.data.essentials.EssentialsIsVanishedProvider.apply(EssentialsIsVanishedProvider.java:35) ~[?:?]
    at codecrafter47.bungeetablistplus.data.essentials.EssentialsIsVanishedProvider.apply(EssentialsIsVanishedProvider.java:29) ~[?:?]
    at codecrafter47.bungeetablistplus.data.bukkit.AbstractDataAccess.lambda$getValue$1(AbstractDataAccess.java:65) ~[?:?]
    at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_72]
    at codecrafter47.bungeetablistplus.data.bukkit.AbstractDataAccess.getValue(AbstractDataAccess.java:65) ~[?:?]
    at codecrafter47.bungeetablistplus.data.bukkit.JoinedDataAccess.getValue(JoinedDataAccess.java:43) ~[?:?]
    at codecrafter47.bungeetablistplus.bukkitbridge.BukkitBridge$DataUpdateTask.lambda$update$7(BukkitBridge.java:337) ~[?:?]

**Comment by CodeCrafter47** [comment]
Which version of essentials are you using?

**Comment by Obatunde** [comment]
To be honest I don't know. I hate how some mods and plugins do not have the version on the file name.
If you believe it is the latest available on Bukkit  2.13.1 
But I am not sure. I will update just to make sure and go back to you.

**Comment by CodeCrafter47** [comment]
Closing this. It's related to a four year old version of essentials which is not relevant anymore. Also recent versions of the plugin should not spam the log files even if there are errors.
