### ISSUE TITLE
Prefix BungeePerms

### ISSUE THREAD

**Issue by FireF0re** [CodeCrafter47/BungeeTabListPlus#92]
I get always this error in BungeeCord.

10:44:23 [SEVERE] [BungeeTabListPlus] An error occurred while querying data from BungeePerms. Make sure you have configured BungeePerms to use it's uuidPlayerDB.
java.lang.NullPointerException
    at net.alpenblock.bungeeperms.User.buildSuffix(User.java:652)
    at net.alpenblock.bungeeperms.User.buildSuffix(User.java:595)
    at codecrafter47.bungeetablistplus.managers.PermissionManager.getSuffixFromBungeePerms(PermissionManager.java:340)
    at codecrafter47.bungeetablistplus.managers.DataManager$$Lambda$17/93798665.apply(Unknown Source)
    at codecrafter47.bungeetablistplus.data.AbstractDataAccess.getRawValue(AbstractDataAccess.java:45)
    at codecrafter47.bungeetablistplus.managers.DataManager.updateData(DataManager.java:62)
    at codecrafter47.bungeetablistplus.managers.DataManager$$Lambda$20/1976166251.run(Unknown Source)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by CodeCrafter47** [comment]
You are not using the latest build of BungeePerms. Your issue has already been fixed.

**Comment by FireF0re** [comment]
Ah, thanks, it works :)
